// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: body/pvt/T01007002.proto

package com.qlcd.qltt.body.pvt;

public final class T01007002 {
  private T01007002() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface _deltacmenuOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qlcd.qltt.body.pvt.T01007002._deltacmenu)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string tactic = 1;</code>
     */
    java.lang.String getTactic();
    /**
     * <code>string tactic = 1;</code>
     */
    com.google.protobuf.ByteString
        getTacticBytes();
  }
  /**
   * Protobuf type {@code com.qlcd.qltt.body.pvt.T01007002._deltacmenu}
   */
  public  static final class _deltacmenu extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.qlcd.qltt.body.pvt.T01007002._deltacmenu)
      _deltacmenuOrBuilder {
    // Use _deltacmenu.newBuilder() to construct.
    private _deltacmenu(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private _deltacmenu() {
      tactic_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private _deltacmenu(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              tactic_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qlcd.qltt.body.pvt.T01007002.internal_static_com_qlcd_qltt_body_pvt_T01007002__deltacmenu_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qlcd.qltt.body.pvt.T01007002.internal_static_com_qlcd_qltt_body_pvt_T01007002__deltacmenu_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qlcd.qltt.body.pvt.T01007002._deltacmenu.class, com.qlcd.qltt.body.pvt.T01007002._deltacmenu.Builder.class);
    }

    public static final int TACTIC_FIELD_NUMBER = 1;
    private volatile java.lang.Object tactic_;
    /**
     * <code>string tactic = 1;</code>
     */
    public java.lang.String getTactic() {
      java.lang.Object ref = tactic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tactic_ = s;
        return s;
      }
    }
    /**
     * <code>string tactic = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTacticBytes() {
      java.lang.Object ref = tactic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tactic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTacticBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tactic_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTacticBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tactic_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qlcd.qltt.body.pvt.T01007002._deltacmenu)) {
        return super.equals(obj);
      }
      com.qlcd.qltt.body.pvt.T01007002._deltacmenu other = (com.qlcd.qltt.body.pvt.T01007002._deltacmenu) obj;

      boolean result = true;
      result = result && getTactic()
          .equals(other.getTactic());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TACTIC_FIELD_NUMBER;
      hash = (53 * hash) + getTactic().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qlcd.qltt.body.pvt.T01007002._deltacmenu parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._deltacmenu parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._deltacmenu parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._deltacmenu parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._deltacmenu parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._deltacmenu parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._deltacmenu parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._deltacmenu parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._deltacmenu parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._deltacmenu parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qlcd.qltt.body.pvt.T01007002._deltacmenu prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qlcd.qltt.body.pvt.T01007002._deltacmenu}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qlcd.qltt.body.pvt.T01007002._deltacmenu)
        com.qlcd.qltt.body.pvt.T01007002._deltacmenuOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qlcd.qltt.body.pvt.T01007002.internal_static_com_qlcd_qltt_body_pvt_T01007002__deltacmenu_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qlcd.qltt.body.pvt.T01007002.internal_static_com_qlcd_qltt_body_pvt_T01007002__deltacmenu_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qlcd.qltt.body.pvt.T01007002._deltacmenu.class, com.qlcd.qltt.body.pvt.T01007002._deltacmenu.Builder.class);
      }

      // Construct using com.qlcd.qltt.body.pvt.T01007002._deltacmenu.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        tactic_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qlcd.qltt.body.pvt.T01007002.internal_static_com_qlcd_qltt_body_pvt_T01007002__deltacmenu_descriptor;
      }

      public com.qlcd.qltt.body.pvt.T01007002._deltacmenu getDefaultInstanceForType() {
        return com.qlcd.qltt.body.pvt.T01007002._deltacmenu.getDefaultInstance();
      }

      public com.qlcd.qltt.body.pvt.T01007002._deltacmenu build() {
        com.qlcd.qltt.body.pvt.T01007002._deltacmenu result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qlcd.qltt.body.pvt.T01007002._deltacmenu buildPartial() {
        com.qlcd.qltt.body.pvt.T01007002._deltacmenu result = new com.qlcd.qltt.body.pvt.T01007002._deltacmenu(this);
        result.tactic_ = tactic_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qlcd.qltt.body.pvt.T01007002._deltacmenu) {
          return mergeFrom((com.qlcd.qltt.body.pvt.T01007002._deltacmenu)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qlcd.qltt.body.pvt.T01007002._deltacmenu other) {
        if (other == com.qlcd.qltt.body.pvt.T01007002._deltacmenu.getDefaultInstance()) return this;
        if (!other.getTactic().isEmpty()) {
          tactic_ = other.tactic_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qlcd.qltt.body.pvt.T01007002._deltacmenu parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qlcd.qltt.body.pvt.T01007002._deltacmenu) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object tactic_ = "";
      /**
       * <code>string tactic = 1;</code>
       */
      public java.lang.String getTactic() {
        java.lang.Object ref = tactic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tactic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tactic = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTacticBytes() {
        java.lang.Object ref = tactic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tactic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tactic = 1;</code>
       */
      public Builder setTactic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tactic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tactic = 1;</code>
       */
      public Builder clearTactic() {
        
        tactic_ = getDefaultInstance().getTactic();
        onChanged();
        return this;
      }
      /**
       * <code>string tactic = 1;</code>
       */
      public Builder setTacticBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tactic_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.qlcd.qltt.body.pvt.T01007002._deltacmenu)
    }

    // @@protoc_insertion_point(class_scope:com.qlcd.qltt.body.pvt.T01007002._deltacmenu)
    private static final com.qlcd.qltt.body.pvt.T01007002._deltacmenu DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qlcd.qltt.body.pvt.T01007002._deltacmenu();
    }

    public static com.qlcd.qltt.body.pvt.T01007002._deltacmenu getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<_deltacmenu>
        PARSER = new com.google.protobuf.AbstractParser<_deltacmenu>() {
      public _deltacmenu parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new _deltacmenu(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<_deltacmenu> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<_deltacmenu> getParserForType() {
      return PARSER;
    }

    public com.qlcd.qltt.body.pvt.T01007002._deltacmenu getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface _reqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qlcd.qltt.body.pvt.T01007002._req)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ttacct = 1;</code>
     */
    java.lang.String getTtacct();
    /**
     * <code>string ttacct = 1;</code>
     */
    com.google.protobuf.ByteString
        getTtacctBytes();

    /**
     * <code>.com.qlcd.qltt.body.pvt.T01007002._deltacmenu dtm = 2;</code>
     */
    boolean hasDtm();
    /**
     * <code>.com.qlcd.qltt.body.pvt.T01007002._deltacmenu dtm = 2;</code>
     */
    com.qlcd.qltt.body.pvt.T01007002._deltacmenu getDtm();
    /**
     * <code>.com.qlcd.qltt.body.pvt.T01007002._deltacmenu dtm = 2;</code>
     */
    com.qlcd.qltt.body.pvt.T01007002._deltacmenuOrBuilder getDtmOrBuilder();
  }
  /**
   * Protobuf type {@code com.qlcd.qltt.body.pvt.T01007002._req}
   */
  public  static final class _req extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.qlcd.qltt.body.pvt.T01007002._req)
      _reqOrBuilder {
    // Use _req.newBuilder() to construct.
    private _req(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private _req() {
      ttacct_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private _req(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              ttacct_ = s;
              break;
            }
            case 18: {
              com.qlcd.qltt.body.pvt.T01007002._deltacmenu.Builder subBuilder = null;
              if (dtm_ != null) {
                subBuilder = dtm_.toBuilder();
              }
              dtm_ = input.readMessage(com.qlcd.qltt.body.pvt.T01007002._deltacmenu.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dtm_);
                dtm_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qlcd.qltt.body.pvt.T01007002.internal_static_com_qlcd_qltt_body_pvt_T01007002__req_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qlcd.qltt.body.pvt.T01007002.internal_static_com_qlcd_qltt_body_pvt_T01007002__req_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qlcd.qltt.body.pvt.T01007002._req.class, com.qlcd.qltt.body.pvt.T01007002._req.Builder.class);
    }

    public static final int TTACCT_FIELD_NUMBER = 1;
    private volatile java.lang.Object ttacct_;
    /**
     * <code>string ttacct = 1;</code>
     */
    public java.lang.String getTtacct() {
      java.lang.Object ref = ttacct_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ttacct_ = s;
        return s;
      }
    }
    /**
     * <code>string ttacct = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTtacctBytes() {
      java.lang.Object ref = ttacct_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ttacct_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DTM_FIELD_NUMBER = 2;
    private com.qlcd.qltt.body.pvt.T01007002._deltacmenu dtm_;
    /**
     * <code>.com.qlcd.qltt.body.pvt.T01007002._deltacmenu dtm = 2;</code>
     */
    public boolean hasDtm() {
      return dtm_ != null;
    }
    /**
     * <code>.com.qlcd.qltt.body.pvt.T01007002._deltacmenu dtm = 2;</code>
     */
    public com.qlcd.qltt.body.pvt.T01007002._deltacmenu getDtm() {
      return dtm_ == null ? com.qlcd.qltt.body.pvt.T01007002._deltacmenu.getDefaultInstance() : dtm_;
    }
    /**
     * <code>.com.qlcd.qltt.body.pvt.T01007002._deltacmenu dtm = 2;</code>
     */
    public com.qlcd.qltt.body.pvt.T01007002._deltacmenuOrBuilder getDtmOrBuilder() {
      return getDtm();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTtacctBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ttacct_);
      }
      if (dtm_ != null) {
        output.writeMessage(2, getDtm());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTtacctBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ttacct_);
      }
      if (dtm_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDtm());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qlcd.qltt.body.pvt.T01007002._req)) {
        return super.equals(obj);
      }
      com.qlcd.qltt.body.pvt.T01007002._req other = (com.qlcd.qltt.body.pvt.T01007002._req) obj;

      boolean result = true;
      result = result && getTtacct()
          .equals(other.getTtacct());
      result = result && (hasDtm() == other.hasDtm());
      if (hasDtm()) {
        result = result && getDtm()
            .equals(other.getDtm());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TTACCT_FIELD_NUMBER;
      hash = (53 * hash) + getTtacct().hashCode();
      if (hasDtm()) {
        hash = (37 * hash) + DTM_FIELD_NUMBER;
        hash = (53 * hash) + getDtm().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qlcd.qltt.body.pvt.T01007002._req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qlcd.qltt.body.pvt.T01007002._req prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qlcd.qltt.body.pvt.T01007002._req}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qlcd.qltt.body.pvt.T01007002._req)
        com.qlcd.qltt.body.pvt.T01007002._reqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qlcd.qltt.body.pvt.T01007002.internal_static_com_qlcd_qltt_body_pvt_T01007002__req_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qlcd.qltt.body.pvt.T01007002.internal_static_com_qlcd_qltt_body_pvt_T01007002__req_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qlcd.qltt.body.pvt.T01007002._req.class, com.qlcd.qltt.body.pvt.T01007002._req.Builder.class);
      }

      // Construct using com.qlcd.qltt.body.pvt.T01007002._req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ttacct_ = "";

        if (dtmBuilder_ == null) {
          dtm_ = null;
        } else {
          dtm_ = null;
          dtmBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qlcd.qltt.body.pvt.T01007002.internal_static_com_qlcd_qltt_body_pvt_T01007002__req_descriptor;
      }

      public com.qlcd.qltt.body.pvt.T01007002._req getDefaultInstanceForType() {
        return com.qlcd.qltt.body.pvt.T01007002._req.getDefaultInstance();
      }

      public com.qlcd.qltt.body.pvt.T01007002._req build() {
        com.qlcd.qltt.body.pvt.T01007002._req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qlcd.qltt.body.pvt.T01007002._req buildPartial() {
        com.qlcd.qltt.body.pvt.T01007002._req result = new com.qlcd.qltt.body.pvt.T01007002._req(this);
        result.ttacct_ = ttacct_;
        if (dtmBuilder_ == null) {
          result.dtm_ = dtm_;
        } else {
          result.dtm_ = dtmBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qlcd.qltt.body.pvt.T01007002._req) {
          return mergeFrom((com.qlcd.qltt.body.pvt.T01007002._req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qlcd.qltt.body.pvt.T01007002._req other) {
        if (other == com.qlcd.qltt.body.pvt.T01007002._req.getDefaultInstance()) return this;
        if (!other.getTtacct().isEmpty()) {
          ttacct_ = other.ttacct_;
          onChanged();
        }
        if (other.hasDtm()) {
          mergeDtm(other.getDtm());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qlcd.qltt.body.pvt.T01007002._req parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qlcd.qltt.body.pvt.T01007002._req) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object ttacct_ = "";
      /**
       * <code>string ttacct = 1;</code>
       */
      public java.lang.String getTtacct() {
        java.lang.Object ref = ttacct_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ttacct_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ttacct = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTtacctBytes() {
        java.lang.Object ref = ttacct_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ttacct_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ttacct = 1;</code>
       */
      public Builder setTtacct(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ttacct_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ttacct = 1;</code>
       */
      public Builder clearTtacct() {
        
        ttacct_ = getDefaultInstance().getTtacct();
        onChanged();
        return this;
      }
      /**
       * <code>string ttacct = 1;</code>
       */
      public Builder setTtacctBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ttacct_ = value;
        onChanged();
        return this;
      }

      private com.qlcd.qltt.body.pvt.T01007002._deltacmenu dtm_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qlcd.qltt.body.pvt.T01007002._deltacmenu, com.qlcd.qltt.body.pvt.T01007002._deltacmenu.Builder, com.qlcd.qltt.body.pvt.T01007002._deltacmenuOrBuilder> dtmBuilder_;
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007002._deltacmenu dtm = 2;</code>
       */
      public boolean hasDtm() {
        return dtmBuilder_ != null || dtm_ != null;
      }
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007002._deltacmenu dtm = 2;</code>
       */
      public com.qlcd.qltt.body.pvt.T01007002._deltacmenu getDtm() {
        if (dtmBuilder_ == null) {
          return dtm_ == null ? com.qlcd.qltt.body.pvt.T01007002._deltacmenu.getDefaultInstance() : dtm_;
        } else {
          return dtmBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007002._deltacmenu dtm = 2;</code>
       */
      public Builder setDtm(com.qlcd.qltt.body.pvt.T01007002._deltacmenu value) {
        if (dtmBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dtm_ = value;
          onChanged();
        } else {
          dtmBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007002._deltacmenu dtm = 2;</code>
       */
      public Builder setDtm(
          com.qlcd.qltt.body.pvt.T01007002._deltacmenu.Builder builderForValue) {
        if (dtmBuilder_ == null) {
          dtm_ = builderForValue.build();
          onChanged();
        } else {
          dtmBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007002._deltacmenu dtm = 2;</code>
       */
      public Builder mergeDtm(com.qlcd.qltt.body.pvt.T01007002._deltacmenu value) {
        if (dtmBuilder_ == null) {
          if (dtm_ != null) {
            dtm_ =
              com.qlcd.qltt.body.pvt.T01007002._deltacmenu.newBuilder(dtm_).mergeFrom(value).buildPartial();
          } else {
            dtm_ = value;
          }
          onChanged();
        } else {
          dtmBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007002._deltacmenu dtm = 2;</code>
       */
      public Builder clearDtm() {
        if (dtmBuilder_ == null) {
          dtm_ = null;
          onChanged();
        } else {
          dtm_ = null;
          dtmBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007002._deltacmenu dtm = 2;</code>
       */
      public com.qlcd.qltt.body.pvt.T01007002._deltacmenu.Builder getDtmBuilder() {
        
        onChanged();
        return getDtmFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007002._deltacmenu dtm = 2;</code>
       */
      public com.qlcd.qltt.body.pvt.T01007002._deltacmenuOrBuilder getDtmOrBuilder() {
        if (dtmBuilder_ != null) {
          return dtmBuilder_.getMessageOrBuilder();
        } else {
          return dtm_ == null ?
              com.qlcd.qltt.body.pvt.T01007002._deltacmenu.getDefaultInstance() : dtm_;
        }
      }
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007002._deltacmenu dtm = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qlcd.qltt.body.pvt.T01007002._deltacmenu, com.qlcd.qltt.body.pvt.T01007002._deltacmenu.Builder, com.qlcd.qltt.body.pvt.T01007002._deltacmenuOrBuilder> 
          getDtmFieldBuilder() {
        if (dtmBuilder_ == null) {
          dtmBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.qlcd.qltt.body.pvt.T01007002._deltacmenu, com.qlcd.qltt.body.pvt.T01007002._deltacmenu.Builder, com.qlcd.qltt.body.pvt.T01007002._deltacmenuOrBuilder>(
                  getDtm(),
                  getParentForChildren(),
                  isClean());
          dtm_ = null;
        }
        return dtmBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.qlcd.qltt.body.pvt.T01007002._req)
    }

    // @@protoc_insertion_point(class_scope:com.qlcd.qltt.body.pvt.T01007002._req)
    private static final com.qlcd.qltt.body.pvt.T01007002._req DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qlcd.qltt.body.pvt.T01007002._req();
    }

    public static com.qlcd.qltt.body.pvt.T01007002._req getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<_req>
        PARSER = new com.google.protobuf.AbstractParser<_req>() {
      public _req parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new _req(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<_req> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<_req> getParserForType() {
      return PARSER;
    }

    public com.qlcd.qltt.body.pvt.T01007002._req getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface _rspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qlcd.qltt.body.pvt.T01007002._rsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    boolean hasRsh();
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    com.qlcd.qltt.body.BppSys._rsp_succhead getRsh();
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder getRshOrBuilder();
  }
  /**
   * Protobuf type {@code com.qlcd.qltt.body.pvt.T01007002._rsp}
   */
  public  static final class _rsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.qlcd.qltt.body.pvt.T01007002._rsp)
      _rspOrBuilder {
    // Use _rsp.newBuilder() to construct.
    private _rsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private _rsp() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private _rsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.qlcd.qltt.body.BppSys._rsp_succhead.Builder subBuilder = null;
              if (rsh_ != null) {
                subBuilder = rsh_.toBuilder();
              }
              rsh_ = input.readMessage(com.qlcd.qltt.body.BppSys._rsp_succhead.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rsh_);
                rsh_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qlcd.qltt.body.pvt.T01007002.internal_static_com_qlcd_qltt_body_pvt_T01007002__rsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qlcd.qltt.body.pvt.T01007002.internal_static_com_qlcd_qltt_body_pvt_T01007002__rsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qlcd.qltt.body.pvt.T01007002._rsp.class, com.qlcd.qltt.body.pvt.T01007002._rsp.Builder.class);
    }

    public static final int RSH_FIELD_NUMBER = 1;
    private com.qlcd.qltt.body.BppSys._rsp_succhead rsh_;
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    public boolean hasRsh() {
      return rsh_ != null;
    }
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    public com.qlcd.qltt.body.BppSys._rsp_succhead getRsh() {
      return rsh_ == null ? com.qlcd.qltt.body.BppSys._rsp_succhead.getDefaultInstance() : rsh_;
    }
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    public com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder getRshOrBuilder() {
      return getRsh();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rsh_ != null) {
        output.writeMessage(1, getRsh());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rsh_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRsh());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qlcd.qltt.body.pvt.T01007002._rsp)) {
        return super.equals(obj);
      }
      com.qlcd.qltt.body.pvt.T01007002._rsp other = (com.qlcd.qltt.body.pvt.T01007002._rsp) obj;

      boolean result = true;
      result = result && (hasRsh() == other.hasRsh());
      if (hasRsh()) {
        result = result && getRsh()
            .equals(other.getRsh());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRsh()) {
        hash = (37 * hash) + RSH_FIELD_NUMBER;
        hash = (53 * hash) + getRsh().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qlcd.qltt.body.pvt.T01007002._rsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._rsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._rsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._rsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._rsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._rsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._rsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._rsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._rsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007002._rsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qlcd.qltt.body.pvt.T01007002._rsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qlcd.qltt.body.pvt.T01007002._rsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qlcd.qltt.body.pvt.T01007002._rsp)
        com.qlcd.qltt.body.pvt.T01007002._rspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qlcd.qltt.body.pvt.T01007002.internal_static_com_qlcd_qltt_body_pvt_T01007002__rsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qlcd.qltt.body.pvt.T01007002.internal_static_com_qlcd_qltt_body_pvt_T01007002__rsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qlcd.qltt.body.pvt.T01007002._rsp.class, com.qlcd.qltt.body.pvt.T01007002._rsp.Builder.class);
      }

      // Construct using com.qlcd.qltt.body.pvt.T01007002._rsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (rshBuilder_ == null) {
          rsh_ = null;
        } else {
          rsh_ = null;
          rshBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qlcd.qltt.body.pvt.T01007002.internal_static_com_qlcd_qltt_body_pvt_T01007002__rsp_descriptor;
      }

      public com.qlcd.qltt.body.pvt.T01007002._rsp getDefaultInstanceForType() {
        return com.qlcd.qltt.body.pvt.T01007002._rsp.getDefaultInstance();
      }

      public com.qlcd.qltt.body.pvt.T01007002._rsp build() {
        com.qlcd.qltt.body.pvt.T01007002._rsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qlcd.qltt.body.pvt.T01007002._rsp buildPartial() {
        com.qlcd.qltt.body.pvt.T01007002._rsp result = new com.qlcd.qltt.body.pvt.T01007002._rsp(this);
        if (rshBuilder_ == null) {
          result.rsh_ = rsh_;
        } else {
          result.rsh_ = rshBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qlcd.qltt.body.pvt.T01007002._rsp) {
          return mergeFrom((com.qlcd.qltt.body.pvt.T01007002._rsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qlcd.qltt.body.pvt.T01007002._rsp other) {
        if (other == com.qlcd.qltt.body.pvt.T01007002._rsp.getDefaultInstance()) return this;
        if (other.hasRsh()) {
          mergeRsh(other.getRsh());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qlcd.qltt.body.pvt.T01007002._rsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qlcd.qltt.body.pvt.T01007002._rsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.qlcd.qltt.body.BppSys._rsp_succhead rsh_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qlcd.qltt.body.BppSys._rsp_succhead, com.qlcd.qltt.body.BppSys._rsp_succhead.Builder, com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder> rshBuilder_;
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public boolean hasRsh() {
        return rshBuilder_ != null || rsh_ != null;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public com.qlcd.qltt.body.BppSys._rsp_succhead getRsh() {
        if (rshBuilder_ == null) {
          return rsh_ == null ? com.qlcd.qltt.body.BppSys._rsp_succhead.getDefaultInstance() : rsh_;
        } else {
          return rshBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder setRsh(com.qlcd.qltt.body.BppSys._rsp_succhead value) {
        if (rshBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rsh_ = value;
          onChanged();
        } else {
          rshBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder setRsh(
          com.qlcd.qltt.body.BppSys._rsp_succhead.Builder builderForValue) {
        if (rshBuilder_ == null) {
          rsh_ = builderForValue.build();
          onChanged();
        } else {
          rshBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder mergeRsh(com.qlcd.qltt.body.BppSys._rsp_succhead value) {
        if (rshBuilder_ == null) {
          if (rsh_ != null) {
            rsh_ =
              com.qlcd.qltt.body.BppSys._rsp_succhead.newBuilder(rsh_).mergeFrom(value).buildPartial();
          } else {
            rsh_ = value;
          }
          onChanged();
        } else {
          rshBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder clearRsh() {
        if (rshBuilder_ == null) {
          rsh_ = null;
          onChanged();
        } else {
          rsh_ = null;
          rshBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public com.qlcd.qltt.body.BppSys._rsp_succhead.Builder getRshBuilder() {
        
        onChanged();
        return getRshFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder getRshOrBuilder() {
        if (rshBuilder_ != null) {
          return rshBuilder_.getMessageOrBuilder();
        } else {
          return rsh_ == null ?
              com.qlcd.qltt.body.BppSys._rsp_succhead.getDefaultInstance() : rsh_;
        }
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qlcd.qltt.body.BppSys._rsp_succhead, com.qlcd.qltt.body.BppSys._rsp_succhead.Builder, com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder> 
          getRshFieldBuilder() {
        if (rshBuilder_ == null) {
          rshBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.qlcd.qltt.body.BppSys._rsp_succhead, com.qlcd.qltt.body.BppSys._rsp_succhead.Builder, com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder>(
                  getRsh(),
                  getParentForChildren(),
                  isClean());
          rsh_ = null;
        }
        return rshBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.qlcd.qltt.body.pvt.T01007002._rsp)
    }

    // @@protoc_insertion_point(class_scope:com.qlcd.qltt.body.pvt.T01007002._rsp)
    private static final com.qlcd.qltt.body.pvt.T01007002._rsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qlcd.qltt.body.pvt.T01007002._rsp();
    }

    public static com.qlcd.qltt.body.pvt.T01007002._rsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<_rsp>
        PARSER = new com.google.protobuf.AbstractParser<_rsp>() {
      public _rsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new _rsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<_rsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<_rsp> getParserForType() {
      return PARSER;
    }

    public com.qlcd.qltt.body.pvt.T01007002._rsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qlcd_qltt_body_pvt_T01007002__deltacmenu_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_qlcd_qltt_body_pvt_T01007002__deltacmenu_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qlcd_qltt_body_pvt_T01007002__req_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_qlcd_qltt_body_pvt_T01007002__req_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qlcd_qltt_body_pvt_T01007002__rsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_qlcd_qltt_body_pvt_T01007002__rsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030body/pvt/T01007002.proto\022 com.qlcd.qlt" +
      "t.body.pvt.T01007002\032\021body/BppSys.proto\"" +
      "\035\n\013_deltacmenu\022\016\n\006tactic\030\001 \001(\t\"R\n\004_req\022\016" +
      "\n\006ttacct\030\001 \001(\t\022:\n\003dtm\030\002 \001(\0132-.com.qlcd.q" +
      "ltt.body.pvt.T01007002._deltacmenu\"=\n\004_r" +
      "sp\0225\n\003rsh\030\001 \001(\0132(.com.qlcd.qltt.body.Bpp" +
      "Sys._rsp_succheadB\030\n\026com.qlcd.qltt.body." +
      "pvtb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.qlcd.qltt.body.BppSys.getDescriptor(),
        }, assigner);
    internal_static_com_qlcd_qltt_body_pvt_T01007002__deltacmenu_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_qlcd_qltt_body_pvt_T01007002__deltacmenu_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_qlcd_qltt_body_pvt_T01007002__deltacmenu_descriptor,
        new java.lang.String[] { "Tactic", });
    internal_static_com_qlcd_qltt_body_pvt_T01007002__req_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_qlcd_qltt_body_pvt_T01007002__req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_qlcd_qltt_body_pvt_T01007002__req_descriptor,
        new java.lang.String[] { "Ttacct", "Dtm", });
    internal_static_com_qlcd_qltt_body_pvt_T01007002__rsp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_qlcd_qltt_body_pvt_T01007002__rsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_qlcd_qltt_body_pvt_T01007002__rsp_descriptor,
        new java.lang.String[] { "Rsh", });
    com.qlcd.qltt.body.BppSys.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
