// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: body/pvt/T01007001.proto

package com.qlcd.qltt.body.pvt;

public final class T01007001 {
  private T01007001() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface _addtacmenuOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qlcd.qltt.body.pvt.T01007001._addtacmenu)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string tactic = 1;</code>
     */
    java.lang.String getTactic();
    /**
     * <code>string tactic = 1;</code>
     */
    com.google.protobuf.ByteString
        getTacticBytes();

    /**
     * <code>string tacname = 2;</code>
     */
    java.lang.String getTacname();
    /**
     * <code>string tacname = 2;</code>
     */
    com.google.protobuf.ByteString
        getTacnameBytes();

    /**
     * <code>string tacdetail = 3;</code>
     */
    java.lang.String getTacdetail();
    /**
     * <code>string tacdetail = 3;</code>
     */
    com.google.protobuf.ByteString
        getTacdetailBytes();
  }
  /**
   * Protobuf type {@code com.qlcd.qltt.body.pvt.T01007001._addtacmenu}
   */
  public  static final class _addtacmenu extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.qlcd.qltt.body.pvt.T01007001._addtacmenu)
      _addtacmenuOrBuilder {
    // Use _addtacmenu.newBuilder() to construct.
    private _addtacmenu(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private _addtacmenu() {
      tactic_ = "";
      tacname_ = "";
      tacdetail_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private _addtacmenu(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              tactic_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              tacname_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              tacdetail_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qlcd.qltt.body.pvt.T01007001.internal_static_com_qlcd_qltt_body_pvt_T01007001__addtacmenu_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qlcd.qltt.body.pvt.T01007001.internal_static_com_qlcd_qltt_body_pvt_T01007001__addtacmenu_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qlcd.qltt.body.pvt.T01007001._addtacmenu.class, com.qlcd.qltt.body.pvt.T01007001._addtacmenu.Builder.class);
    }

    public static final int TACTIC_FIELD_NUMBER = 1;
    private volatile java.lang.Object tactic_;
    /**
     * <code>string tactic = 1;</code>
     */
    public java.lang.String getTactic() {
      java.lang.Object ref = tactic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tactic_ = s;
        return s;
      }
    }
    /**
     * <code>string tactic = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTacticBytes() {
      java.lang.Object ref = tactic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tactic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TACNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object tacname_;
    /**
     * <code>string tacname = 2;</code>
     */
    public java.lang.String getTacname() {
      java.lang.Object ref = tacname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tacname_ = s;
        return s;
      }
    }
    /**
     * <code>string tacname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTacnameBytes() {
      java.lang.Object ref = tacname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tacname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TACDETAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object tacdetail_;
    /**
     * <code>string tacdetail = 3;</code>
     */
    public java.lang.String getTacdetail() {
      java.lang.Object ref = tacdetail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tacdetail_ = s;
        return s;
      }
    }
    /**
     * <code>string tacdetail = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTacdetailBytes() {
      java.lang.Object ref = tacdetail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tacdetail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTacticBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tactic_);
      }
      if (!getTacnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tacname_);
      }
      if (!getTacdetailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tacdetail_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTacticBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tactic_);
      }
      if (!getTacnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tacname_);
      }
      if (!getTacdetailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tacdetail_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qlcd.qltt.body.pvt.T01007001._addtacmenu)) {
        return super.equals(obj);
      }
      com.qlcd.qltt.body.pvt.T01007001._addtacmenu other = (com.qlcd.qltt.body.pvt.T01007001._addtacmenu) obj;

      boolean result = true;
      result = result && getTactic()
          .equals(other.getTactic());
      result = result && getTacname()
          .equals(other.getTacname());
      result = result && getTacdetail()
          .equals(other.getTacdetail());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TACTIC_FIELD_NUMBER;
      hash = (53 * hash) + getTactic().hashCode();
      hash = (37 * hash) + TACNAME_FIELD_NUMBER;
      hash = (53 * hash) + getTacname().hashCode();
      hash = (37 * hash) + TACDETAIL_FIELD_NUMBER;
      hash = (53 * hash) + getTacdetail().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qlcd.qltt.body.pvt.T01007001._addtacmenu parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._addtacmenu parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._addtacmenu parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._addtacmenu parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._addtacmenu parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._addtacmenu parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._addtacmenu parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._addtacmenu parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._addtacmenu parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._addtacmenu parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qlcd.qltt.body.pvt.T01007001._addtacmenu prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qlcd.qltt.body.pvt.T01007001._addtacmenu}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qlcd.qltt.body.pvt.T01007001._addtacmenu)
        com.qlcd.qltt.body.pvt.T01007001._addtacmenuOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qlcd.qltt.body.pvt.T01007001.internal_static_com_qlcd_qltt_body_pvt_T01007001__addtacmenu_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qlcd.qltt.body.pvt.T01007001.internal_static_com_qlcd_qltt_body_pvt_T01007001__addtacmenu_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qlcd.qltt.body.pvt.T01007001._addtacmenu.class, com.qlcd.qltt.body.pvt.T01007001._addtacmenu.Builder.class);
      }

      // Construct using com.qlcd.qltt.body.pvt.T01007001._addtacmenu.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        tactic_ = "";

        tacname_ = "";

        tacdetail_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qlcd.qltt.body.pvt.T01007001.internal_static_com_qlcd_qltt_body_pvt_T01007001__addtacmenu_descriptor;
      }

      public com.qlcd.qltt.body.pvt.T01007001._addtacmenu getDefaultInstanceForType() {
        return com.qlcd.qltt.body.pvt.T01007001._addtacmenu.getDefaultInstance();
      }

      public com.qlcd.qltt.body.pvt.T01007001._addtacmenu build() {
        com.qlcd.qltt.body.pvt.T01007001._addtacmenu result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qlcd.qltt.body.pvt.T01007001._addtacmenu buildPartial() {
        com.qlcd.qltt.body.pvt.T01007001._addtacmenu result = new com.qlcd.qltt.body.pvt.T01007001._addtacmenu(this);
        result.tactic_ = tactic_;
        result.tacname_ = tacname_;
        result.tacdetail_ = tacdetail_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qlcd.qltt.body.pvt.T01007001._addtacmenu) {
          return mergeFrom((com.qlcd.qltt.body.pvt.T01007001._addtacmenu)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qlcd.qltt.body.pvt.T01007001._addtacmenu other) {
        if (other == com.qlcd.qltt.body.pvt.T01007001._addtacmenu.getDefaultInstance()) return this;
        if (!other.getTactic().isEmpty()) {
          tactic_ = other.tactic_;
          onChanged();
        }
        if (!other.getTacname().isEmpty()) {
          tacname_ = other.tacname_;
          onChanged();
        }
        if (!other.getTacdetail().isEmpty()) {
          tacdetail_ = other.tacdetail_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qlcd.qltt.body.pvt.T01007001._addtacmenu parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qlcd.qltt.body.pvt.T01007001._addtacmenu) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object tactic_ = "";
      /**
       * <code>string tactic = 1;</code>
       */
      public java.lang.String getTactic() {
        java.lang.Object ref = tactic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tactic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tactic = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTacticBytes() {
        java.lang.Object ref = tactic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tactic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tactic = 1;</code>
       */
      public Builder setTactic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tactic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tactic = 1;</code>
       */
      public Builder clearTactic() {
        
        tactic_ = getDefaultInstance().getTactic();
        onChanged();
        return this;
      }
      /**
       * <code>string tactic = 1;</code>
       */
      public Builder setTacticBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tactic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tacname_ = "";
      /**
       * <code>string tacname = 2;</code>
       */
      public java.lang.String getTacname() {
        java.lang.Object ref = tacname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tacname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tacname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTacnameBytes() {
        java.lang.Object ref = tacname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tacname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tacname = 2;</code>
       */
      public Builder setTacname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tacname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tacname = 2;</code>
       */
      public Builder clearTacname() {
        
        tacname_ = getDefaultInstance().getTacname();
        onChanged();
        return this;
      }
      /**
       * <code>string tacname = 2;</code>
       */
      public Builder setTacnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tacname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tacdetail_ = "";
      /**
       * <code>string tacdetail = 3;</code>
       */
      public java.lang.String getTacdetail() {
        java.lang.Object ref = tacdetail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tacdetail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tacdetail = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTacdetailBytes() {
        java.lang.Object ref = tacdetail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tacdetail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tacdetail = 3;</code>
       */
      public Builder setTacdetail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tacdetail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tacdetail = 3;</code>
       */
      public Builder clearTacdetail() {
        
        tacdetail_ = getDefaultInstance().getTacdetail();
        onChanged();
        return this;
      }
      /**
       * <code>string tacdetail = 3;</code>
       */
      public Builder setTacdetailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tacdetail_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.qlcd.qltt.body.pvt.T01007001._addtacmenu)
    }

    // @@protoc_insertion_point(class_scope:com.qlcd.qltt.body.pvt.T01007001._addtacmenu)
    private static final com.qlcd.qltt.body.pvt.T01007001._addtacmenu DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qlcd.qltt.body.pvt.T01007001._addtacmenu();
    }

    public static com.qlcd.qltt.body.pvt.T01007001._addtacmenu getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<_addtacmenu>
        PARSER = new com.google.protobuf.AbstractParser<_addtacmenu>() {
      public _addtacmenu parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new _addtacmenu(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<_addtacmenu> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<_addtacmenu> getParserForType() {
      return PARSER;
    }

    public com.qlcd.qltt.body.pvt.T01007001._addtacmenu getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface _reqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qlcd.qltt.body.pvt.T01007001._req)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ttacct = 1;</code>
     */
    java.lang.String getTtacct();
    /**
     * <code>string ttacct = 1;</code>
     */
    com.google.protobuf.ByteString
        getTtacctBytes();

    /**
     * <code>.com.qlcd.qltt.body.pvt.T01007001._addtacmenu atm = 2;</code>
     */
    boolean hasAtm();
    /**
     * <code>.com.qlcd.qltt.body.pvt.T01007001._addtacmenu atm = 2;</code>
     */
    com.qlcd.qltt.body.pvt.T01007001._addtacmenu getAtm();
    /**
     * <code>.com.qlcd.qltt.body.pvt.T01007001._addtacmenu atm = 2;</code>
     */
    com.qlcd.qltt.body.pvt.T01007001._addtacmenuOrBuilder getAtmOrBuilder();
  }
  /**
   * Protobuf type {@code com.qlcd.qltt.body.pvt.T01007001._req}
   */
  public  static final class _req extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.qlcd.qltt.body.pvt.T01007001._req)
      _reqOrBuilder {
    // Use _req.newBuilder() to construct.
    private _req(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private _req() {
      ttacct_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private _req(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              ttacct_ = s;
              break;
            }
            case 18: {
              com.qlcd.qltt.body.pvt.T01007001._addtacmenu.Builder subBuilder = null;
              if (atm_ != null) {
                subBuilder = atm_.toBuilder();
              }
              atm_ = input.readMessage(com.qlcd.qltt.body.pvt.T01007001._addtacmenu.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(atm_);
                atm_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qlcd.qltt.body.pvt.T01007001.internal_static_com_qlcd_qltt_body_pvt_T01007001__req_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qlcd.qltt.body.pvt.T01007001.internal_static_com_qlcd_qltt_body_pvt_T01007001__req_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qlcd.qltt.body.pvt.T01007001._req.class, com.qlcd.qltt.body.pvt.T01007001._req.Builder.class);
    }

    public static final int TTACCT_FIELD_NUMBER = 1;
    private volatile java.lang.Object ttacct_;
    /**
     * <code>string ttacct = 1;</code>
     */
    public java.lang.String getTtacct() {
      java.lang.Object ref = ttacct_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ttacct_ = s;
        return s;
      }
    }
    /**
     * <code>string ttacct = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTtacctBytes() {
      java.lang.Object ref = ttacct_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ttacct_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATM_FIELD_NUMBER = 2;
    private com.qlcd.qltt.body.pvt.T01007001._addtacmenu atm_;
    /**
     * <code>.com.qlcd.qltt.body.pvt.T01007001._addtacmenu atm = 2;</code>
     */
    public boolean hasAtm() {
      return atm_ != null;
    }
    /**
     * <code>.com.qlcd.qltt.body.pvt.T01007001._addtacmenu atm = 2;</code>
     */
    public com.qlcd.qltt.body.pvt.T01007001._addtacmenu getAtm() {
      return atm_ == null ? com.qlcd.qltt.body.pvt.T01007001._addtacmenu.getDefaultInstance() : atm_;
    }
    /**
     * <code>.com.qlcd.qltt.body.pvt.T01007001._addtacmenu atm = 2;</code>
     */
    public com.qlcd.qltt.body.pvt.T01007001._addtacmenuOrBuilder getAtmOrBuilder() {
      return getAtm();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTtacctBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ttacct_);
      }
      if (atm_ != null) {
        output.writeMessage(2, getAtm());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTtacctBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ttacct_);
      }
      if (atm_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getAtm());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qlcd.qltt.body.pvt.T01007001._req)) {
        return super.equals(obj);
      }
      com.qlcd.qltt.body.pvt.T01007001._req other = (com.qlcd.qltt.body.pvt.T01007001._req) obj;

      boolean result = true;
      result = result && getTtacct()
          .equals(other.getTtacct());
      result = result && (hasAtm() == other.hasAtm());
      if (hasAtm()) {
        result = result && getAtm()
            .equals(other.getAtm());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TTACCT_FIELD_NUMBER;
      hash = (53 * hash) + getTtacct().hashCode();
      if (hasAtm()) {
        hash = (37 * hash) + ATM_FIELD_NUMBER;
        hash = (53 * hash) + getAtm().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qlcd.qltt.body.pvt.T01007001._req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qlcd.qltt.body.pvt.T01007001._req prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qlcd.qltt.body.pvt.T01007001._req}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qlcd.qltt.body.pvt.T01007001._req)
        com.qlcd.qltt.body.pvt.T01007001._reqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qlcd.qltt.body.pvt.T01007001.internal_static_com_qlcd_qltt_body_pvt_T01007001__req_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qlcd.qltt.body.pvt.T01007001.internal_static_com_qlcd_qltt_body_pvt_T01007001__req_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qlcd.qltt.body.pvt.T01007001._req.class, com.qlcd.qltt.body.pvt.T01007001._req.Builder.class);
      }

      // Construct using com.qlcd.qltt.body.pvt.T01007001._req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ttacct_ = "";

        if (atmBuilder_ == null) {
          atm_ = null;
        } else {
          atm_ = null;
          atmBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qlcd.qltt.body.pvt.T01007001.internal_static_com_qlcd_qltt_body_pvt_T01007001__req_descriptor;
      }

      public com.qlcd.qltt.body.pvt.T01007001._req getDefaultInstanceForType() {
        return com.qlcd.qltt.body.pvt.T01007001._req.getDefaultInstance();
      }

      public com.qlcd.qltt.body.pvt.T01007001._req build() {
        com.qlcd.qltt.body.pvt.T01007001._req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qlcd.qltt.body.pvt.T01007001._req buildPartial() {
        com.qlcd.qltt.body.pvt.T01007001._req result = new com.qlcd.qltt.body.pvt.T01007001._req(this);
        result.ttacct_ = ttacct_;
        if (atmBuilder_ == null) {
          result.atm_ = atm_;
        } else {
          result.atm_ = atmBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qlcd.qltt.body.pvt.T01007001._req) {
          return mergeFrom((com.qlcd.qltt.body.pvt.T01007001._req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qlcd.qltt.body.pvt.T01007001._req other) {
        if (other == com.qlcd.qltt.body.pvt.T01007001._req.getDefaultInstance()) return this;
        if (!other.getTtacct().isEmpty()) {
          ttacct_ = other.ttacct_;
          onChanged();
        }
        if (other.hasAtm()) {
          mergeAtm(other.getAtm());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qlcd.qltt.body.pvt.T01007001._req parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qlcd.qltt.body.pvt.T01007001._req) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object ttacct_ = "";
      /**
       * <code>string ttacct = 1;</code>
       */
      public java.lang.String getTtacct() {
        java.lang.Object ref = ttacct_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ttacct_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ttacct = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTtacctBytes() {
        java.lang.Object ref = ttacct_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ttacct_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ttacct = 1;</code>
       */
      public Builder setTtacct(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ttacct_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ttacct = 1;</code>
       */
      public Builder clearTtacct() {
        
        ttacct_ = getDefaultInstance().getTtacct();
        onChanged();
        return this;
      }
      /**
       * <code>string ttacct = 1;</code>
       */
      public Builder setTtacctBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ttacct_ = value;
        onChanged();
        return this;
      }

      private com.qlcd.qltt.body.pvt.T01007001._addtacmenu atm_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qlcd.qltt.body.pvt.T01007001._addtacmenu, com.qlcd.qltt.body.pvt.T01007001._addtacmenu.Builder, com.qlcd.qltt.body.pvt.T01007001._addtacmenuOrBuilder> atmBuilder_;
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007001._addtacmenu atm = 2;</code>
       */
      public boolean hasAtm() {
        return atmBuilder_ != null || atm_ != null;
      }
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007001._addtacmenu atm = 2;</code>
       */
      public com.qlcd.qltt.body.pvt.T01007001._addtacmenu getAtm() {
        if (atmBuilder_ == null) {
          return atm_ == null ? com.qlcd.qltt.body.pvt.T01007001._addtacmenu.getDefaultInstance() : atm_;
        } else {
          return atmBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007001._addtacmenu atm = 2;</code>
       */
      public Builder setAtm(com.qlcd.qltt.body.pvt.T01007001._addtacmenu value) {
        if (atmBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          atm_ = value;
          onChanged();
        } else {
          atmBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007001._addtacmenu atm = 2;</code>
       */
      public Builder setAtm(
          com.qlcd.qltt.body.pvt.T01007001._addtacmenu.Builder builderForValue) {
        if (atmBuilder_ == null) {
          atm_ = builderForValue.build();
          onChanged();
        } else {
          atmBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007001._addtacmenu atm = 2;</code>
       */
      public Builder mergeAtm(com.qlcd.qltt.body.pvt.T01007001._addtacmenu value) {
        if (atmBuilder_ == null) {
          if (atm_ != null) {
            atm_ =
              com.qlcd.qltt.body.pvt.T01007001._addtacmenu.newBuilder(atm_).mergeFrom(value).buildPartial();
          } else {
            atm_ = value;
          }
          onChanged();
        } else {
          atmBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007001._addtacmenu atm = 2;</code>
       */
      public Builder clearAtm() {
        if (atmBuilder_ == null) {
          atm_ = null;
          onChanged();
        } else {
          atm_ = null;
          atmBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007001._addtacmenu atm = 2;</code>
       */
      public com.qlcd.qltt.body.pvt.T01007001._addtacmenu.Builder getAtmBuilder() {
        
        onChanged();
        return getAtmFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007001._addtacmenu atm = 2;</code>
       */
      public com.qlcd.qltt.body.pvt.T01007001._addtacmenuOrBuilder getAtmOrBuilder() {
        if (atmBuilder_ != null) {
          return atmBuilder_.getMessageOrBuilder();
        } else {
          return atm_ == null ?
              com.qlcd.qltt.body.pvt.T01007001._addtacmenu.getDefaultInstance() : atm_;
        }
      }
      /**
       * <code>.com.qlcd.qltt.body.pvt.T01007001._addtacmenu atm = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qlcd.qltt.body.pvt.T01007001._addtacmenu, com.qlcd.qltt.body.pvt.T01007001._addtacmenu.Builder, com.qlcd.qltt.body.pvt.T01007001._addtacmenuOrBuilder> 
          getAtmFieldBuilder() {
        if (atmBuilder_ == null) {
          atmBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.qlcd.qltt.body.pvt.T01007001._addtacmenu, com.qlcd.qltt.body.pvt.T01007001._addtacmenu.Builder, com.qlcd.qltt.body.pvt.T01007001._addtacmenuOrBuilder>(
                  getAtm(),
                  getParentForChildren(),
                  isClean());
          atm_ = null;
        }
        return atmBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.qlcd.qltt.body.pvt.T01007001._req)
    }

    // @@protoc_insertion_point(class_scope:com.qlcd.qltt.body.pvt.T01007001._req)
    private static final com.qlcd.qltt.body.pvt.T01007001._req DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qlcd.qltt.body.pvt.T01007001._req();
    }

    public static com.qlcd.qltt.body.pvt.T01007001._req getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<_req>
        PARSER = new com.google.protobuf.AbstractParser<_req>() {
      public _req parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new _req(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<_req> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<_req> getParserForType() {
      return PARSER;
    }

    public com.qlcd.qltt.body.pvt.T01007001._req getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface _rspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qlcd.qltt.body.pvt.T01007001._rsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    boolean hasRsh();
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    com.qlcd.qltt.body.BppSys._rsp_succhead getRsh();
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder getRshOrBuilder();
  }
  /**
   * Protobuf type {@code com.qlcd.qltt.body.pvt.T01007001._rsp}
   */
  public  static final class _rsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.qlcd.qltt.body.pvt.T01007001._rsp)
      _rspOrBuilder {
    // Use _rsp.newBuilder() to construct.
    private _rsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private _rsp() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private _rsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.qlcd.qltt.body.BppSys._rsp_succhead.Builder subBuilder = null;
              if (rsh_ != null) {
                subBuilder = rsh_.toBuilder();
              }
              rsh_ = input.readMessage(com.qlcd.qltt.body.BppSys._rsp_succhead.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rsh_);
                rsh_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qlcd.qltt.body.pvt.T01007001.internal_static_com_qlcd_qltt_body_pvt_T01007001__rsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qlcd.qltt.body.pvt.T01007001.internal_static_com_qlcd_qltt_body_pvt_T01007001__rsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qlcd.qltt.body.pvt.T01007001._rsp.class, com.qlcd.qltt.body.pvt.T01007001._rsp.Builder.class);
    }

    public static final int RSH_FIELD_NUMBER = 1;
    private com.qlcd.qltt.body.BppSys._rsp_succhead rsh_;
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    public boolean hasRsh() {
      return rsh_ != null;
    }
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    public com.qlcd.qltt.body.BppSys._rsp_succhead getRsh() {
      return rsh_ == null ? com.qlcd.qltt.body.BppSys._rsp_succhead.getDefaultInstance() : rsh_;
    }
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    public com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder getRshOrBuilder() {
      return getRsh();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rsh_ != null) {
        output.writeMessage(1, getRsh());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rsh_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRsh());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qlcd.qltt.body.pvt.T01007001._rsp)) {
        return super.equals(obj);
      }
      com.qlcd.qltt.body.pvt.T01007001._rsp other = (com.qlcd.qltt.body.pvt.T01007001._rsp) obj;

      boolean result = true;
      result = result && (hasRsh() == other.hasRsh());
      if (hasRsh()) {
        result = result && getRsh()
            .equals(other.getRsh());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRsh()) {
        hash = (37 * hash) + RSH_FIELD_NUMBER;
        hash = (53 * hash) + getRsh().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qlcd.qltt.body.pvt.T01007001._rsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._rsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._rsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._rsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._rsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._rsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._rsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._rsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._rsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T01007001._rsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qlcd.qltt.body.pvt.T01007001._rsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qlcd.qltt.body.pvt.T01007001._rsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qlcd.qltt.body.pvt.T01007001._rsp)
        com.qlcd.qltt.body.pvt.T01007001._rspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qlcd.qltt.body.pvt.T01007001.internal_static_com_qlcd_qltt_body_pvt_T01007001__rsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qlcd.qltt.body.pvt.T01007001.internal_static_com_qlcd_qltt_body_pvt_T01007001__rsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qlcd.qltt.body.pvt.T01007001._rsp.class, com.qlcd.qltt.body.pvt.T01007001._rsp.Builder.class);
      }

      // Construct using com.qlcd.qltt.body.pvt.T01007001._rsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (rshBuilder_ == null) {
          rsh_ = null;
        } else {
          rsh_ = null;
          rshBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qlcd.qltt.body.pvt.T01007001.internal_static_com_qlcd_qltt_body_pvt_T01007001__rsp_descriptor;
      }

      public com.qlcd.qltt.body.pvt.T01007001._rsp getDefaultInstanceForType() {
        return com.qlcd.qltt.body.pvt.T01007001._rsp.getDefaultInstance();
      }

      public com.qlcd.qltt.body.pvt.T01007001._rsp build() {
        com.qlcd.qltt.body.pvt.T01007001._rsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qlcd.qltt.body.pvt.T01007001._rsp buildPartial() {
        com.qlcd.qltt.body.pvt.T01007001._rsp result = new com.qlcd.qltt.body.pvt.T01007001._rsp(this);
        if (rshBuilder_ == null) {
          result.rsh_ = rsh_;
        } else {
          result.rsh_ = rshBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qlcd.qltt.body.pvt.T01007001._rsp) {
          return mergeFrom((com.qlcd.qltt.body.pvt.T01007001._rsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qlcd.qltt.body.pvt.T01007001._rsp other) {
        if (other == com.qlcd.qltt.body.pvt.T01007001._rsp.getDefaultInstance()) return this;
        if (other.hasRsh()) {
          mergeRsh(other.getRsh());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qlcd.qltt.body.pvt.T01007001._rsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qlcd.qltt.body.pvt.T01007001._rsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.qlcd.qltt.body.BppSys._rsp_succhead rsh_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qlcd.qltt.body.BppSys._rsp_succhead, com.qlcd.qltt.body.BppSys._rsp_succhead.Builder, com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder> rshBuilder_;
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public boolean hasRsh() {
        return rshBuilder_ != null || rsh_ != null;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public com.qlcd.qltt.body.BppSys._rsp_succhead getRsh() {
        if (rshBuilder_ == null) {
          return rsh_ == null ? com.qlcd.qltt.body.BppSys._rsp_succhead.getDefaultInstance() : rsh_;
        } else {
          return rshBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder setRsh(com.qlcd.qltt.body.BppSys._rsp_succhead value) {
        if (rshBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rsh_ = value;
          onChanged();
        } else {
          rshBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder setRsh(
          com.qlcd.qltt.body.BppSys._rsp_succhead.Builder builderForValue) {
        if (rshBuilder_ == null) {
          rsh_ = builderForValue.build();
          onChanged();
        } else {
          rshBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder mergeRsh(com.qlcd.qltt.body.BppSys._rsp_succhead value) {
        if (rshBuilder_ == null) {
          if (rsh_ != null) {
            rsh_ =
              com.qlcd.qltt.body.BppSys._rsp_succhead.newBuilder(rsh_).mergeFrom(value).buildPartial();
          } else {
            rsh_ = value;
          }
          onChanged();
        } else {
          rshBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder clearRsh() {
        if (rshBuilder_ == null) {
          rsh_ = null;
          onChanged();
        } else {
          rsh_ = null;
          rshBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public com.qlcd.qltt.body.BppSys._rsp_succhead.Builder getRshBuilder() {
        
        onChanged();
        return getRshFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder getRshOrBuilder() {
        if (rshBuilder_ != null) {
          return rshBuilder_.getMessageOrBuilder();
        } else {
          return rsh_ == null ?
              com.qlcd.qltt.body.BppSys._rsp_succhead.getDefaultInstance() : rsh_;
        }
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qlcd.qltt.body.BppSys._rsp_succhead, com.qlcd.qltt.body.BppSys._rsp_succhead.Builder, com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder> 
          getRshFieldBuilder() {
        if (rshBuilder_ == null) {
          rshBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.qlcd.qltt.body.BppSys._rsp_succhead, com.qlcd.qltt.body.BppSys._rsp_succhead.Builder, com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder>(
                  getRsh(),
                  getParentForChildren(),
                  isClean());
          rsh_ = null;
        }
        return rshBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.qlcd.qltt.body.pvt.T01007001._rsp)
    }

    // @@protoc_insertion_point(class_scope:com.qlcd.qltt.body.pvt.T01007001._rsp)
    private static final com.qlcd.qltt.body.pvt.T01007001._rsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qlcd.qltt.body.pvt.T01007001._rsp();
    }

    public static com.qlcd.qltt.body.pvt.T01007001._rsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<_rsp>
        PARSER = new com.google.protobuf.AbstractParser<_rsp>() {
      public _rsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new _rsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<_rsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<_rsp> getParserForType() {
      return PARSER;
    }

    public com.qlcd.qltt.body.pvt.T01007001._rsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qlcd_qltt_body_pvt_T01007001__addtacmenu_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_qlcd_qltt_body_pvt_T01007001__addtacmenu_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qlcd_qltt_body_pvt_T01007001__req_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_qlcd_qltt_body_pvt_T01007001__req_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qlcd_qltt_body_pvt_T01007001__rsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_qlcd_qltt_body_pvt_T01007001__rsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030body/pvt/T01007001.proto\022 com.qlcd.qlt" +
      "t.body.pvt.T01007001\032\021body/BppSys.proto\"" +
      "A\n\013_addtacmenu\022\016\n\006tactic\030\001 \001(\t\022\017\n\007tacnam" +
      "e\030\002 \001(\t\022\021\n\ttacdetail\030\003 \001(\t\"R\n\004_req\022\016\n\006tt" +
      "acct\030\001 \001(\t\022:\n\003atm\030\002 \001(\0132-.com.qlcd.qltt." +
      "body.pvt.T01007001._addtacmenu\"=\n\004_rsp\0225" +
      "\n\003rsh\030\001 \001(\0132(.com.qlcd.qltt.body.BppSys." +
      "_rsp_succheadB\030\n\026com.qlcd.qltt.body.pvtb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.qlcd.qltt.body.BppSys.getDescriptor(),
        }, assigner);
    internal_static_com_qlcd_qltt_body_pvt_T01007001__addtacmenu_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_qlcd_qltt_body_pvt_T01007001__addtacmenu_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_qlcd_qltt_body_pvt_T01007001__addtacmenu_descriptor,
        new java.lang.String[] { "Tactic", "Tacname", "Tacdetail", });
    internal_static_com_qlcd_qltt_body_pvt_T01007001__req_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_qlcd_qltt_body_pvt_T01007001__req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_qlcd_qltt_body_pvt_T01007001__req_descriptor,
        new java.lang.String[] { "Ttacct", "Atm", });
    internal_static_com_qlcd_qltt_body_pvt_T01007001__rsp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_qlcd_qltt_body_pvt_T01007001__rsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_qlcd_qltt_body_pvt_T01007001__rsp_descriptor,
        new java.lang.String[] { "Rsh", });
    com.qlcd.qltt.body.BppSys.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
