// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: body/pvt/T02002003.proto

package com.qlcd.qltt.body.pvt;

public final class T02002003 {
  private T02002003() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface _reqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qlcd.qltt.body.pvt.T02002003._req)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string tactic = 1;</code>
     */
    java.lang.String getTactic();
    /**
     * <code>string tactic = 1;</code>
     */
    com.google.protobuf.ByteString
        getTacticBytes();
  }
  /**
   * Protobuf type {@code com.qlcd.qltt.body.pvt.T02002003._req}
   */
  public  static final class _req extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.qlcd.qltt.body.pvt.T02002003._req)
      _reqOrBuilder {
    // Use _req.newBuilder() to construct.
    private _req(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private _req() {
      tactic_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private _req(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              tactic_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qlcd.qltt.body.pvt.T02002003.internal_static_com_qlcd_qltt_body_pvt_T02002003__req_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qlcd.qltt.body.pvt.T02002003.internal_static_com_qlcd_qltt_body_pvt_T02002003__req_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qlcd.qltt.body.pvt.T02002003._req.class, com.qlcd.qltt.body.pvt.T02002003._req.Builder.class);
    }

    public static final int TACTIC_FIELD_NUMBER = 1;
    private volatile java.lang.Object tactic_;
    /**
     * <code>string tactic = 1;</code>
     */
    public java.lang.String getTactic() {
      java.lang.Object ref = tactic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tactic_ = s;
        return s;
      }
    }
    /**
     * <code>string tactic = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTacticBytes() {
      java.lang.Object ref = tactic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tactic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTacticBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tactic_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTacticBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tactic_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qlcd.qltt.body.pvt.T02002003._req)) {
        return super.equals(obj);
      }
      com.qlcd.qltt.body.pvt.T02002003._req other = (com.qlcd.qltt.body.pvt.T02002003._req) obj;

      boolean result = true;
      result = result && getTactic()
          .equals(other.getTactic());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TACTIC_FIELD_NUMBER;
      hash = (53 * hash) + getTactic().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qlcd.qltt.body.pvt.T02002003._req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qlcd.qltt.body.pvt.T02002003._req prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qlcd.qltt.body.pvt.T02002003._req}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qlcd.qltt.body.pvt.T02002003._req)
        com.qlcd.qltt.body.pvt.T02002003._reqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qlcd.qltt.body.pvt.T02002003.internal_static_com_qlcd_qltt_body_pvt_T02002003__req_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qlcd.qltt.body.pvt.T02002003.internal_static_com_qlcd_qltt_body_pvt_T02002003__req_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qlcd.qltt.body.pvt.T02002003._req.class, com.qlcd.qltt.body.pvt.T02002003._req.Builder.class);
      }

      // Construct using com.qlcd.qltt.body.pvt.T02002003._req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        tactic_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qlcd.qltt.body.pvt.T02002003.internal_static_com_qlcd_qltt_body_pvt_T02002003__req_descriptor;
      }

      public com.qlcd.qltt.body.pvt.T02002003._req getDefaultInstanceForType() {
        return com.qlcd.qltt.body.pvt.T02002003._req.getDefaultInstance();
      }

      public com.qlcd.qltt.body.pvt.T02002003._req build() {
        com.qlcd.qltt.body.pvt.T02002003._req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qlcd.qltt.body.pvt.T02002003._req buildPartial() {
        com.qlcd.qltt.body.pvt.T02002003._req result = new com.qlcd.qltt.body.pvt.T02002003._req(this);
        result.tactic_ = tactic_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qlcd.qltt.body.pvt.T02002003._req) {
          return mergeFrom((com.qlcd.qltt.body.pvt.T02002003._req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qlcd.qltt.body.pvt.T02002003._req other) {
        if (other == com.qlcd.qltt.body.pvt.T02002003._req.getDefaultInstance()) return this;
        if (!other.getTactic().isEmpty()) {
          tactic_ = other.tactic_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qlcd.qltt.body.pvt.T02002003._req parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qlcd.qltt.body.pvt.T02002003._req) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object tactic_ = "";
      /**
       * <code>string tactic = 1;</code>
       */
      public java.lang.String getTactic() {
        java.lang.Object ref = tactic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tactic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tactic = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTacticBytes() {
        java.lang.Object ref = tactic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tactic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tactic = 1;</code>
       */
      public Builder setTactic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tactic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tactic = 1;</code>
       */
      public Builder clearTactic() {
        
        tactic_ = getDefaultInstance().getTactic();
        onChanged();
        return this;
      }
      /**
       * <code>string tactic = 1;</code>
       */
      public Builder setTacticBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tactic_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.qlcd.qltt.body.pvt.T02002003._req)
    }

    // @@protoc_insertion_point(class_scope:com.qlcd.qltt.body.pvt.T02002003._req)
    private static final com.qlcd.qltt.body.pvt.T02002003._req DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qlcd.qltt.body.pvt.T02002003._req();
    }

    public static com.qlcd.qltt.body.pvt.T02002003._req getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<_req>
        PARSER = new com.google.protobuf.AbstractParser<_req>() {
      public _req parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new _req(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<_req> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<_req> getParserForType() {
      return PARSER;
    }

    public com.qlcd.qltt.body.pvt.T02002003._req getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface _combeleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qlcd.qltt.body.pvt.T02002003._combele)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string srctactic = 1;</code>
     */
    java.lang.String getSrctactic();
    /**
     * <code>string srctactic = 1;</code>
     */
    com.google.protobuf.ByteString
        getSrctacticBytes();

    /**
     * <code>int32 srctacticprm = 2;</code>
     */
    int getSrctacticprm();

    /**
     * <code>string srctacname = 3;</code>
     */
    java.lang.String getSrctacname();
    /**
     * <code>string srctacname = 3;</code>
     */
    com.google.protobuf.ByteString
        getSrctacnameBytes();
  }
  /**
   * Protobuf type {@code com.qlcd.qltt.body.pvt.T02002003._combele}
   */
  public  static final class _combele extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.qlcd.qltt.body.pvt.T02002003._combele)
      _combeleOrBuilder {
    // Use _combele.newBuilder() to construct.
    private _combele(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private _combele() {
      srctactic_ = "";
      srctacticprm_ = 0;
      srctacname_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private _combele(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              srctactic_ = s;
              break;
            }
            case 16: {

              srctacticprm_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              srctacname_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qlcd.qltt.body.pvt.T02002003.internal_static_com_qlcd_qltt_body_pvt_T02002003__combele_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qlcd.qltt.body.pvt.T02002003.internal_static_com_qlcd_qltt_body_pvt_T02002003__combele_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qlcd.qltt.body.pvt.T02002003._combele.class, com.qlcd.qltt.body.pvt.T02002003._combele.Builder.class);
    }

    public static final int SRCTACTIC_FIELD_NUMBER = 1;
    private volatile java.lang.Object srctactic_;
    /**
     * <code>string srctactic = 1;</code>
     */
    public java.lang.String getSrctactic() {
      java.lang.Object ref = srctactic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        srctactic_ = s;
        return s;
      }
    }
    /**
     * <code>string srctactic = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSrctacticBytes() {
      java.lang.Object ref = srctactic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srctactic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SRCTACTICPRM_FIELD_NUMBER = 2;
    private int srctacticprm_;
    /**
     * <code>int32 srctacticprm = 2;</code>
     */
    public int getSrctacticprm() {
      return srctacticprm_;
    }

    public static final int SRCTACNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object srctacname_;
    /**
     * <code>string srctacname = 3;</code>
     */
    public java.lang.String getSrctacname() {
      java.lang.Object ref = srctacname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        srctacname_ = s;
        return s;
      }
    }
    /**
     * <code>string srctacname = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSrctacnameBytes() {
      java.lang.Object ref = srctacname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srctacname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSrctacticBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, srctactic_);
      }
      if (srctacticprm_ != 0) {
        output.writeInt32(2, srctacticprm_);
      }
      if (!getSrctacnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, srctacname_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSrctacticBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, srctactic_);
      }
      if (srctacticprm_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, srctacticprm_);
      }
      if (!getSrctacnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, srctacname_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qlcd.qltt.body.pvt.T02002003._combele)) {
        return super.equals(obj);
      }
      com.qlcd.qltt.body.pvt.T02002003._combele other = (com.qlcd.qltt.body.pvt.T02002003._combele) obj;

      boolean result = true;
      result = result && getSrctactic()
          .equals(other.getSrctactic());
      result = result && (getSrctacticprm()
          == other.getSrctacticprm());
      result = result && getSrctacname()
          .equals(other.getSrctacname());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SRCTACTIC_FIELD_NUMBER;
      hash = (53 * hash) + getSrctactic().hashCode();
      hash = (37 * hash) + SRCTACTICPRM_FIELD_NUMBER;
      hash = (53 * hash) + getSrctacticprm();
      hash = (37 * hash) + SRCTACNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSrctacname().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qlcd.qltt.body.pvt.T02002003._combele parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._combele parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._combele parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._combele parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._combele parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._combele parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._combele parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._combele parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._combele parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._combele parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qlcd.qltt.body.pvt.T02002003._combele prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qlcd.qltt.body.pvt.T02002003._combele}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qlcd.qltt.body.pvt.T02002003._combele)
        com.qlcd.qltt.body.pvt.T02002003._combeleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qlcd.qltt.body.pvt.T02002003.internal_static_com_qlcd_qltt_body_pvt_T02002003__combele_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qlcd.qltt.body.pvt.T02002003.internal_static_com_qlcd_qltt_body_pvt_T02002003__combele_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qlcd.qltt.body.pvt.T02002003._combele.class, com.qlcd.qltt.body.pvt.T02002003._combele.Builder.class);
      }

      // Construct using com.qlcd.qltt.body.pvt.T02002003._combele.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        srctactic_ = "";

        srctacticprm_ = 0;

        srctacname_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qlcd.qltt.body.pvt.T02002003.internal_static_com_qlcd_qltt_body_pvt_T02002003__combele_descriptor;
      }

      public com.qlcd.qltt.body.pvt.T02002003._combele getDefaultInstanceForType() {
        return com.qlcd.qltt.body.pvt.T02002003._combele.getDefaultInstance();
      }

      public com.qlcd.qltt.body.pvt.T02002003._combele build() {
        com.qlcd.qltt.body.pvt.T02002003._combele result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qlcd.qltt.body.pvt.T02002003._combele buildPartial() {
        com.qlcd.qltt.body.pvt.T02002003._combele result = new com.qlcd.qltt.body.pvt.T02002003._combele(this);
        result.srctactic_ = srctactic_;
        result.srctacticprm_ = srctacticprm_;
        result.srctacname_ = srctacname_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qlcd.qltt.body.pvt.T02002003._combele) {
          return mergeFrom((com.qlcd.qltt.body.pvt.T02002003._combele)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qlcd.qltt.body.pvt.T02002003._combele other) {
        if (other == com.qlcd.qltt.body.pvt.T02002003._combele.getDefaultInstance()) return this;
        if (!other.getSrctactic().isEmpty()) {
          srctactic_ = other.srctactic_;
          onChanged();
        }
        if (other.getSrctacticprm() != 0) {
          setSrctacticprm(other.getSrctacticprm());
        }
        if (!other.getSrctacname().isEmpty()) {
          srctacname_ = other.srctacname_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qlcd.qltt.body.pvt.T02002003._combele parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qlcd.qltt.body.pvt.T02002003._combele) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object srctactic_ = "";
      /**
       * <code>string srctactic = 1;</code>
       */
      public java.lang.String getSrctactic() {
        java.lang.Object ref = srctactic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          srctactic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string srctactic = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSrctacticBytes() {
        java.lang.Object ref = srctactic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          srctactic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string srctactic = 1;</code>
       */
      public Builder setSrctactic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        srctactic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string srctactic = 1;</code>
       */
      public Builder clearSrctactic() {
        
        srctactic_ = getDefaultInstance().getSrctactic();
        onChanged();
        return this;
      }
      /**
       * <code>string srctactic = 1;</code>
       */
      public Builder setSrctacticBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        srctactic_ = value;
        onChanged();
        return this;
      }

      private int srctacticprm_ ;
      /**
       * <code>int32 srctacticprm = 2;</code>
       */
      public int getSrctacticprm() {
        return srctacticprm_;
      }
      /**
       * <code>int32 srctacticprm = 2;</code>
       */
      public Builder setSrctacticprm(int value) {
        
        srctacticprm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 srctacticprm = 2;</code>
       */
      public Builder clearSrctacticprm() {
        
        srctacticprm_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object srctacname_ = "";
      /**
       * <code>string srctacname = 3;</code>
       */
      public java.lang.String getSrctacname() {
        java.lang.Object ref = srctacname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          srctacname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string srctacname = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSrctacnameBytes() {
        java.lang.Object ref = srctacname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          srctacname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string srctacname = 3;</code>
       */
      public Builder setSrctacname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        srctacname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string srctacname = 3;</code>
       */
      public Builder clearSrctacname() {
        
        srctacname_ = getDefaultInstance().getSrctacname();
        onChanged();
        return this;
      }
      /**
       * <code>string srctacname = 3;</code>
       */
      public Builder setSrctacnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        srctacname_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.qlcd.qltt.body.pvt.T02002003._combele)
    }

    // @@protoc_insertion_point(class_scope:com.qlcd.qltt.body.pvt.T02002003._combele)
    private static final com.qlcd.qltt.body.pvt.T02002003._combele DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qlcd.qltt.body.pvt.T02002003._combele();
    }

    public static com.qlcd.qltt.body.pvt.T02002003._combele getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<_combele>
        PARSER = new com.google.protobuf.AbstractParser<_combele>() {
      public _combele parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new _combele(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<_combele> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<_combele> getParserForType() {
      return PARSER;
    }

    public com.qlcd.qltt.body.pvt.T02002003._combele getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface _rspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qlcd.qltt.body.pvt.T02002003._rsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    boolean hasRsh();
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    com.qlcd.qltt.body.BppSys._rsp_succhead getRsh();
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder getRshOrBuilder();

    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
     */
    java.util.List<com.qlcd.qltt.body.pvt.T02002003._combele> 
        getCbelistList();
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
     */
    com.qlcd.qltt.body.pvt.T02002003._combele getCbelist(int index);
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
     */
    int getCbelistCount();
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
     */
    java.util.List<? extends com.qlcd.qltt.body.pvt.T02002003._combeleOrBuilder> 
        getCbelistOrBuilderList();
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
     */
    com.qlcd.qltt.body.pvt.T02002003._combeleOrBuilder getCbelistOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.qlcd.qltt.body.pvt.T02002003._rsp}
   */
  public  static final class _rsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.qlcd.qltt.body.pvt.T02002003._rsp)
      _rspOrBuilder {
    // Use _rsp.newBuilder() to construct.
    private _rsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private _rsp() {
      cbelist_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private _rsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.qlcd.qltt.body.BppSys._rsp_succhead.Builder subBuilder = null;
              if (rsh_ != null) {
                subBuilder = rsh_.toBuilder();
              }
              rsh_ = input.readMessage(com.qlcd.qltt.body.BppSys._rsp_succhead.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rsh_);
                rsh_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                cbelist_ = new java.util.ArrayList<com.qlcd.qltt.body.pvt.T02002003._combele>();
                mutable_bitField0_ |= 0x00000002;
              }
              cbelist_.add(
                  input.readMessage(com.qlcd.qltt.body.pvt.T02002003._combele.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          cbelist_ = java.util.Collections.unmodifiableList(cbelist_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qlcd.qltt.body.pvt.T02002003.internal_static_com_qlcd_qltt_body_pvt_T02002003__rsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qlcd.qltt.body.pvt.T02002003.internal_static_com_qlcd_qltt_body_pvt_T02002003__rsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qlcd.qltt.body.pvt.T02002003._rsp.class, com.qlcd.qltt.body.pvt.T02002003._rsp.Builder.class);
    }

    private int bitField0_;
    public static final int RSH_FIELD_NUMBER = 1;
    private com.qlcd.qltt.body.BppSys._rsp_succhead rsh_;
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    public boolean hasRsh() {
      return rsh_ != null;
    }
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    public com.qlcd.qltt.body.BppSys._rsp_succhead getRsh() {
      return rsh_ == null ? com.qlcd.qltt.body.BppSys._rsp_succhead.getDefaultInstance() : rsh_;
    }
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    public com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder getRshOrBuilder() {
      return getRsh();
    }

    public static final int CBELIST_FIELD_NUMBER = 2;
    private java.util.List<com.qlcd.qltt.body.pvt.T02002003._combele> cbelist_;
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
     */
    public java.util.List<com.qlcd.qltt.body.pvt.T02002003._combele> getCbelistList() {
      return cbelist_;
    }
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
     */
    public java.util.List<? extends com.qlcd.qltt.body.pvt.T02002003._combeleOrBuilder> 
        getCbelistOrBuilderList() {
      return cbelist_;
    }
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
     */
    public int getCbelistCount() {
      return cbelist_.size();
    }
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
     */
    public com.qlcd.qltt.body.pvt.T02002003._combele getCbelist(int index) {
      return cbelist_.get(index);
    }
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
     */
    public com.qlcd.qltt.body.pvt.T02002003._combeleOrBuilder getCbelistOrBuilder(
        int index) {
      return cbelist_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rsh_ != null) {
        output.writeMessage(1, getRsh());
      }
      for (int i = 0; i < cbelist_.size(); i++) {
        output.writeMessage(2, cbelist_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rsh_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRsh());
      }
      for (int i = 0; i < cbelist_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, cbelist_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qlcd.qltt.body.pvt.T02002003._rsp)) {
        return super.equals(obj);
      }
      com.qlcd.qltt.body.pvt.T02002003._rsp other = (com.qlcd.qltt.body.pvt.T02002003._rsp) obj;

      boolean result = true;
      result = result && (hasRsh() == other.hasRsh());
      if (hasRsh()) {
        result = result && getRsh()
            .equals(other.getRsh());
      }
      result = result && getCbelistList()
          .equals(other.getCbelistList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRsh()) {
        hash = (37 * hash) + RSH_FIELD_NUMBER;
        hash = (53 * hash) + getRsh().hashCode();
      }
      if (getCbelistCount() > 0) {
        hash = (37 * hash) + CBELIST_FIELD_NUMBER;
        hash = (53 * hash) + getCbelistList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qlcd.qltt.body.pvt.T02002003._rsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._rsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._rsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._rsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._rsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._rsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._rsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._rsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._rsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02002003._rsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qlcd.qltt.body.pvt.T02002003._rsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qlcd.qltt.body.pvt.T02002003._rsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qlcd.qltt.body.pvt.T02002003._rsp)
        com.qlcd.qltt.body.pvt.T02002003._rspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qlcd.qltt.body.pvt.T02002003.internal_static_com_qlcd_qltt_body_pvt_T02002003__rsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qlcd.qltt.body.pvt.T02002003.internal_static_com_qlcd_qltt_body_pvt_T02002003__rsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qlcd.qltt.body.pvt.T02002003._rsp.class, com.qlcd.qltt.body.pvt.T02002003._rsp.Builder.class);
      }

      // Construct using com.qlcd.qltt.body.pvt.T02002003._rsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCbelistFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (rshBuilder_ == null) {
          rsh_ = null;
        } else {
          rsh_ = null;
          rshBuilder_ = null;
        }
        if (cbelistBuilder_ == null) {
          cbelist_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          cbelistBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qlcd.qltt.body.pvt.T02002003.internal_static_com_qlcd_qltt_body_pvt_T02002003__rsp_descriptor;
      }

      public com.qlcd.qltt.body.pvt.T02002003._rsp getDefaultInstanceForType() {
        return com.qlcd.qltt.body.pvt.T02002003._rsp.getDefaultInstance();
      }

      public com.qlcd.qltt.body.pvt.T02002003._rsp build() {
        com.qlcd.qltt.body.pvt.T02002003._rsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qlcd.qltt.body.pvt.T02002003._rsp buildPartial() {
        com.qlcd.qltt.body.pvt.T02002003._rsp result = new com.qlcd.qltt.body.pvt.T02002003._rsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (rshBuilder_ == null) {
          result.rsh_ = rsh_;
        } else {
          result.rsh_ = rshBuilder_.build();
        }
        if (cbelistBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            cbelist_ = java.util.Collections.unmodifiableList(cbelist_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.cbelist_ = cbelist_;
        } else {
          result.cbelist_ = cbelistBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qlcd.qltt.body.pvt.T02002003._rsp) {
          return mergeFrom((com.qlcd.qltt.body.pvt.T02002003._rsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qlcd.qltt.body.pvt.T02002003._rsp other) {
        if (other == com.qlcd.qltt.body.pvt.T02002003._rsp.getDefaultInstance()) return this;
        if (other.hasRsh()) {
          mergeRsh(other.getRsh());
        }
        if (cbelistBuilder_ == null) {
          if (!other.cbelist_.isEmpty()) {
            if (cbelist_.isEmpty()) {
              cbelist_ = other.cbelist_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureCbelistIsMutable();
              cbelist_.addAll(other.cbelist_);
            }
            onChanged();
          }
        } else {
          if (!other.cbelist_.isEmpty()) {
            if (cbelistBuilder_.isEmpty()) {
              cbelistBuilder_.dispose();
              cbelistBuilder_ = null;
              cbelist_ = other.cbelist_;
              bitField0_ = (bitField0_ & ~0x00000002);
              cbelistBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCbelistFieldBuilder() : null;
            } else {
              cbelistBuilder_.addAllMessages(other.cbelist_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qlcd.qltt.body.pvt.T02002003._rsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qlcd.qltt.body.pvt.T02002003._rsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.qlcd.qltt.body.BppSys._rsp_succhead rsh_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qlcd.qltt.body.BppSys._rsp_succhead, com.qlcd.qltt.body.BppSys._rsp_succhead.Builder, com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder> rshBuilder_;
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public boolean hasRsh() {
        return rshBuilder_ != null || rsh_ != null;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public com.qlcd.qltt.body.BppSys._rsp_succhead getRsh() {
        if (rshBuilder_ == null) {
          return rsh_ == null ? com.qlcd.qltt.body.BppSys._rsp_succhead.getDefaultInstance() : rsh_;
        } else {
          return rshBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder setRsh(com.qlcd.qltt.body.BppSys._rsp_succhead value) {
        if (rshBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rsh_ = value;
          onChanged();
        } else {
          rshBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder setRsh(
          com.qlcd.qltt.body.BppSys._rsp_succhead.Builder builderForValue) {
        if (rshBuilder_ == null) {
          rsh_ = builderForValue.build();
          onChanged();
        } else {
          rshBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder mergeRsh(com.qlcd.qltt.body.BppSys._rsp_succhead value) {
        if (rshBuilder_ == null) {
          if (rsh_ != null) {
            rsh_ =
              com.qlcd.qltt.body.BppSys._rsp_succhead.newBuilder(rsh_).mergeFrom(value).buildPartial();
          } else {
            rsh_ = value;
          }
          onChanged();
        } else {
          rshBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder clearRsh() {
        if (rshBuilder_ == null) {
          rsh_ = null;
          onChanged();
        } else {
          rsh_ = null;
          rshBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public com.qlcd.qltt.body.BppSys._rsp_succhead.Builder getRshBuilder() {
        
        onChanged();
        return getRshFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder getRshOrBuilder() {
        if (rshBuilder_ != null) {
          return rshBuilder_.getMessageOrBuilder();
        } else {
          return rsh_ == null ?
              com.qlcd.qltt.body.BppSys._rsp_succhead.getDefaultInstance() : rsh_;
        }
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qlcd.qltt.body.BppSys._rsp_succhead, com.qlcd.qltt.body.BppSys._rsp_succhead.Builder, com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder> 
          getRshFieldBuilder() {
        if (rshBuilder_ == null) {
          rshBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.qlcd.qltt.body.BppSys._rsp_succhead, com.qlcd.qltt.body.BppSys._rsp_succhead.Builder, com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder>(
                  getRsh(),
                  getParentForChildren(),
                  isClean());
          rsh_ = null;
        }
        return rshBuilder_;
      }

      private java.util.List<com.qlcd.qltt.body.pvt.T02002003._combele> cbelist_ =
        java.util.Collections.emptyList();
      private void ensureCbelistIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          cbelist_ = new java.util.ArrayList<com.qlcd.qltt.body.pvt.T02002003._combele>(cbelist_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.qlcd.qltt.body.pvt.T02002003._combele, com.qlcd.qltt.body.pvt.T02002003._combele.Builder, com.qlcd.qltt.body.pvt.T02002003._combeleOrBuilder> cbelistBuilder_;

      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public java.util.List<com.qlcd.qltt.body.pvt.T02002003._combele> getCbelistList() {
        if (cbelistBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cbelist_);
        } else {
          return cbelistBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public int getCbelistCount() {
        if (cbelistBuilder_ == null) {
          return cbelist_.size();
        } else {
          return cbelistBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public com.qlcd.qltt.body.pvt.T02002003._combele getCbelist(int index) {
        if (cbelistBuilder_ == null) {
          return cbelist_.get(index);
        } else {
          return cbelistBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public Builder setCbelist(
          int index, com.qlcd.qltt.body.pvt.T02002003._combele value) {
        if (cbelistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCbelistIsMutable();
          cbelist_.set(index, value);
          onChanged();
        } else {
          cbelistBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public Builder setCbelist(
          int index, com.qlcd.qltt.body.pvt.T02002003._combele.Builder builderForValue) {
        if (cbelistBuilder_ == null) {
          ensureCbelistIsMutable();
          cbelist_.set(index, builderForValue.build());
          onChanged();
        } else {
          cbelistBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public Builder addCbelist(com.qlcd.qltt.body.pvt.T02002003._combele value) {
        if (cbelistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCbelistIsMutable();
          cbelist_.add(value);
          onChanged();
        } else {
          cbelistBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public Builder addCbelist(
          int index, com.qlcd.qltt.body.pvt.T02002003._combele value) {
        if (cbelistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCbelistIsMutable();
          cbelist_.add(index, value);
          onChanged();
        } else {
          cbelistBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public Builder addCbelist(
          com.qlcd.qltt.body.pvt.T02002003._combele.Builder builderForValue) {
        if (cbelistBuilder_ == null) {
          ensureCbelistIsMutable();
          cbelist_.add(builderForValue.build());
          onChanged();
        } else {
          cbelistBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public Builder addCbelist(
          int index, com.qlcd.qltt.body.pvt.T02002003._combele.Builder builderForValue) {
        if (cbelistBuilder_ == null) {
          ensureCbelistIsMutable();
          cbelist_.add(index, builderForValue.build());
          onChanged();
        } else {
          cbelistBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public Builder addAllCbelist(
          java.lang.Iterable<? extends com.qlcd.qltt.body.pvt.T02002003._combele> values) {
        if (cbelistBuilder_ == null) {
          ensureCbelistIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cbelist_);
          onChanged();
        } else {
          cbelistBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public Builder clearCbelist() {
        if (cbelistBuilder_ == null) {
          cbelist_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          cbelistBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public Builder removeCbelist(int index) {
        if (cbelistBuilder_ == null) {
          ensureCbelistIsMutable();
          cbelist_.remove(index);
          onChanged();
        } else {
          cbelistBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public com.qlcd.qltt.body.pvt.T02002003._combele.Builder getCbelistBuilder(
          int index) {
        return getCbelistFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public com.qlcd.qltt.body.pvt.T02002003._combeleOrBuilder getCbelistOrBuilder(
          int index) {
        if (cbelistBuilder_ == null) {
          return cbelist_.get(index);  } else {
          return cbelistBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public java.util.List<? extends com.qlcd.qltt.body.pvt.T02002003._combeleOrBuilder> 
           getCbelistOrBuilderList() {
        if (cbelistBuilder_ != null) {
          return cbelistBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cbelist_);
        }
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public com.qlcd.qltt.body.pvt.T02002003._combele.Builder addCbelistBuilder() {
        return getCbelistFieldBuilder().addBuilder(
            com.qlcd.qltt.body.pvt.T02002003._combele.getDefaultInstance());
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public com.qlcd.qltt.body.pvt.T02002003._combele.Builder addCbelistBuilder(
          int index) {
        return getCbelistFieldBuilder().addBuilder(
            index, com.qlcd.qltt.body.pvt.T02002003._combele.getDefaultInstance());
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02002003._combele cbelist = 2;</code>
       */
      public java.util.List<com.qlcd.qltt.body.pvt.T02002003._combele.Builder> 
           getCbelistBuilderList() {
        return getCbelistFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.qlcd.qltt.body.pvt.T02002003._combele, com.qlcd.qltt.body.pvt.T02002003._combele.Builder, com.qlcd.qltt.body.pvt.T02002003._combeleOrBuilder> 
          getCbelistFieldBuilder() {
        if (cbelistBuilder_ == null) {
          cbelistBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.qlcd.qltt.body.pvt.T02002003._combele, com.qlcd.qltt.body.pvt.T02002003._combele.Builder, com.qlcd.qltt.body.pvt.T02002003._combeleOrBuilder>(
                  cbelist_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          cbelist_ = null;
        }
        return cbelistBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.qlcd.qltt.body.pvt.T02002003._rsp)
    }

    // @@protoc_insertion_point(class_scope:com.qlcd.qltt.body.pvt.T02002003._rsp)
    private static final com.qlcd.qltt.body.pvt.T02002003._rsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qlcd.qltt.body.pvt.T02002003._rsp();
    }

    public static com.qlcd.qltt.body.pvt.T02002003._rsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<_rsp>
        PARSER = new com.google.protobuf.AbstractParser<_rsp>() {
      public _rsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new _rsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<_rsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<_rsp> getParserForType() {
      return PARSER;
    }

    public com.qlcd.qltt.body.pvt.T02002003._rsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qlcd_qltt_body_pvt_T02002003__req_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_qlcd_qltt_body_pvt_T02002003__req_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qlcd_qltt_body_pvt_T02002003__combele_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_qlcd_qltt_body_pvt_T02002003__combele_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qlcd_qltt_body_pvt_T02002003__rsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_qlcd_qltt_body_pvt_T02002003__rsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030body/pvt/T02002003.proto\022 com.qlcd.qlt" +
      "t.body.pvt.T02002003\032\021body/BppSys.proto\"" +
      "\026\n\004_req\022\016\n\006tactic\030\001 \001(\t\"G\n\010_combele\022\021\n\ts" +
      "rctactic\030\001 \001(\t\022\024\n\014srctacticprm\030\002 \001(\005\022\022\n\n" +
      "srctacname\030\003 \001(\t\"z\n\004_rsp\0225\n\003rsh\030\001 \001(\0132(." +
      "com.qlcd.qltt.body.BppSys._rsp_succhead\022" +
      ";\n\007cbelist\030\002 \003(\0132*.com.qlcd.qltt.body.pv" +
      "t.T02002003._combeleB\030\n\026com.qlcd.qltt.bo" +
      "dy.pvtb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.qlcd.qltt.body.BppSys.getDescriptor(),
        }, assigner);
    internal_static_com_qlcd_qltt_body_pvt_T02002003__req_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_qlcd_qltt_body_pvt_T02002003__req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_qlcd_qltt_body_pvt_T02002003__req_descriptor,
        new java.lang.String[] { "Tactic", });
    internal_static_com_qlcd_qltt_body_pvt_T02002003__combele_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_qlcd_qltt_body_pvt_T02002003__combele_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_qlcd_qltt_body_pvt_T02002003__combele_descriptor,
        new java.lang.String[] { "Srctactic", "Srctacticprm", "Srctacname", });
    internal_static_com_qlcd_qltt_body_pvt_T02002003__rsp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_qlcd_qltt_body_pvt_T02002003__rsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_qlcd_qltt_body_pvt_T02002003__rsp_descriptor,
        new java.lang.String[] { "Rsh", "Cbelist", });
    com.qlcd.qltt.body.BppSys.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
