// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: body/pvt/T02007002.proto

package com.qlcd.qltt.body.pvt;

public final class T02007002 {
  private T02007002() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface _reqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qlcd.qltt.body.pvt.T02007002._req)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
     */
    boolean hasPgreq();
    /**
     * <code>.com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
     */
    com.qlcd.qltt.body.BppBiz._page_req getPgreq();
    /**
     * <code>.com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
     */
    com.qlcd.qltt.body.BppBiz._page_reqOrBuilder getPgreqOrBuilder();

    /**
     * <code>string label = 2;</code>
     */
    java.lang.String getLabel();
    /**
     * <code>string label = 2;</code>
     */
    com.google.protobuf.ByteString
        getLabelBytes();
  }
  /**
   * Protobuf type {@code com.qlcd.qltt.body.pvt.T02007002._req}
   */
  public  static final class _req extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.qlcd.qltt.body.pvt.T02007002._req)
      _reqOrBuilder {
    // Use _req.newBuilder() to construct.
    private _req(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private _req() {
      label_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private _req(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.qlcd.qltt.body.BppBiz._page_req.Builder subBuilder = null;
              if (pgreq_ != null) {
                subBuilder = pgreq_.toBuilder();
              }
              pgreq_ = input.readMessage(com.qlcd.qltt.body.BppBiz._page_req.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pgreq_);
                pgreq_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              label_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qlcd.qltt.body.pvt.T02007002.internal_static_com_qlcd_qltt_body_pvt_T02007002__req_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qlcd.qltt.body.pvt.T02007002.internal_static_com_qlcd_qltt_body_pvt_T02007002__req_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qlcd.qltt.body.pvt.T02007002._req.class, com.qlcd.qltt.body.pvt.T02007002._req.Builder.class);
    }

    public static final int PGREQ_FIELD_NUMBER = 1;
    private com.qlcd.qltt.body.BppBiz._page_req pgreq_;
    /**
     * <code>.com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
     */
    public boolean hasPgreq() {
      return pgreq_ != null;
    }
    /**
     * <code>.com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
     */
    public com.qlcd.qltt.body.BppBiz._page_req getPgreq() {
      return pgreq_ == null ? com.qlcd.qltt.body.BppBiz._page_req.getDefaultInstance() : pgreq_;
    }
    /**
     * <code>.com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
     */
    public com.qlcd.qltt.body.BppBiz._page_reqOrBuilder getPgreqOrBuilder() {
      return getPgreq();
    }

    public static final int LABEL_FIELD_NUMBER = 2;
    private volatile java.lang.Object label_;
    /**
     * <code>string label = 2;</code>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      }
    }
    /**
     * <code>string label = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pgreq_ != null) {
        output.writeMessage(1, getPgreq());
      }
      if (!getLabelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, label_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pgreq_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPgreq());
      }
      if (!getLabelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, label_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qlcd.qltt.body.pvt.T02007002._req)) {
        return super.equals(obj);
      }
      com.qlcd.qltt.body.pvt.T02007002._req other = (com.qlcd.qltt.body.pvt.T02007002._req) obj;

      boolean result = true;
      result = result && (hasPgreq() == other.hasPgreq());
      if (hasPgreq()) {
        result = result && getPgreq()
            .equals(other.getPgreq());
      }
      result = result && getLabel()
          .equals(other.getLabel());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPgreq()) {
        hash = (37 * hash) + PGREQ_FIELD_NUMBER;
        hash = (53 * hash) + getPgreq().hashCode();
      }
      hash = (37 * hash) + LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getLabel().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qlcd.qltt.body.pvt.T02007002._req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qlcd.qltt.body.pvt.T02007002._req prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qlcd.qltt.body.pvt.T02007002._req}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qlcd.qltt.body.pvt.T02007002._req)
        com.qlcd.qltt.body.pvt.T02007002._reqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qlcd.qltt.body.pvt.T02007002.internal_static_com_qlcd_qltt_body_pvt_T02007002__req_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qlcd.qltt.body.pvt.T02007002.internal_static_com_qlcd_qltt_body_pvt_T02007002__req_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qlcd.qltt.body.pvt.T02007002._req.class, com.qlcd.qltt.body.pvt.T02007002._req.Builder.class);
      }

      // Construct using com.qlcd.qltt.body.pvt.T02007002._req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (pgreqBuilder_ == null) {
          pgreq_ = null;
        } else {
          pgreq_ = null;
          pgreqBuilder_ = null;
        }
        label_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qlcd.qltt.body.pvt.T02007002.internal_static_com_qlcd_qltt_body_pvt_T02007002__req_descriptor;
      }

      public com.qlcd.qltt.body.pvt.T02007002._req getDefaultInstanceForType() {
        return com.qlcd.qltt.body.pvt.T02007002._req.getDefaultInstance();
      }

      public com.qlcd.qltt.body.pvt.T02007002._req build() {
        com.qlcd.qltt.body.pvt.T02007002._req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qlcd.qltt.body.pvt.T02007002._req buildPartial() {
        com.qlcd.qltt.body.pvt.T02007002._req result = new com.qlcd.qltt.body.pvt.T02007002._req(this);
        if (pgreqBuilder_ == null) {
          result.pgreq_ = pgreq_;
        } else {
          result.pgreq_ = pgreqBuilder_.build();
        }
        result.label_ = label_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qlcd.qltt.body.pvt.T02007002._req) {
          return mergeFrom((com.qlcd.qltt.body.pvt.T02007002._req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qlcd.qltt.body.pvt.T02007002._req other) {
        if (other == com.qlcd.qltt.body.pvt.T02007002._req.getDefaultInstance()) return this;
        if (other.hasPgreq()) {
          mergePgreq(other.getPgreq());
        }
        if (!other.getLabel().isEmpty()) {
          label_ = other.label_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qlcd.qltt.body.pvt.T02007002._req parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qlcd.qltt.body.pvt.T02007002._req) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.qlcd.qltt.body.BppBiz._page_req pgreq_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qlcd.qltt.body.BppBiz._page_req, com.qlcd.qltt.body.BppBiz._page_req.Builder, com.qlcd.qltt.body.BppBiz._page_reqOrBuilder> pgreqBuilder_;
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      public boolean hasPgreq() {
        return pgreqBuilder_ != null || pgreq_ != null;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      public com.qlcd.qltt.body.BppBiz._page_req getPgreq() {
        if (pgreqBuilder_ == null) {
          return pgreq_ == null ? com.qlcd.qltt.body.BppBiz._page_req.getDefaultInstance() : pgreq_;
        } else {
          return pgreqBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      public Builder setPgreq(com.qlcd.qltt.body.BppBiz._page_req value) {
        if (pgreqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pgreq_ = value;
          onChanged();
        } else {
          pgreqBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      public Builder setPgreq(
          com.qlcd.qltt.body.BppBiz._page_req.Builder builderForValue) {
        if (pgreqBuilder_ == null) {
          pgreq_ = builderForValue.build();
          onChanged();
        } else {
          pgreqBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      public Builder mergePgreq(com.qlcd.qltt.body.BppBiz._page_req value) {
        if (pgreqBuilder_ == null) {
          if (pgreq_ != null) {
            pgreq_ =
              com.qlcd.qltt.body.BppBiz._page_req.newBuilder(pgreq_).mergeFrom(value).buildPartial();
          } else {
            pgreq_ = value;
          }
          onChanged();
        } else {
          pgreqBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      public Builder clearPgreq() {
        if (pgreqBuilder_ == null) {
          pgreq_ = null;
          onChanged();
        } else {
          pgreq_ = null;
          pgreqBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      public com.qlcd.qltt.body.BppBiz._page_req.Builder getPgreqBuilder() {
        
        onChanged();
        return getPgreqFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      public com.qlcd.qltt.body.BppBiz._page_reqOrBuilder getPgreqOrBuilder() {
        if (pgreqBuilder_ != null) {
          return pgreqBuilder_.getMessageOrBuilder();
        } else {
          return pgreq_ == null ?
              com.qlcd.qltt.body.BppBiz._page_req.getDefaultInstance() : pgreq_;
        }
      }
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qlcd.qltt.body.BppBiz._page_req, com.qlcd.qltt.body.BppBiz._page_req.Builder, com.qlcd.qltt.body.BppBiz._page_reqOrBuilder> 
          getPgreqFieldBuilder() {
        if (pgreqBuilder_ == null) {
          pgreqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.qlcd.qltt.body.BppBiz._page_req, com.qlcd.qltt.body.BppBiz._page_req.Builder, com.qlcd.qltt.body.BppBiz._page_reqOrBuilder>(
                  getPgreq(),
                  getParentForChildren(),
                  isClean());
          pgreq_ = null;
        }
        return pgreqBuilder_;
      }

      private java.lang.Object label_ = "";
      /**
       * <code>string label = 2;</code>
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string label = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string label = 2;</code>
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string label = 2;</code>
       */
      public Builder clearLabel() {
        
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <code>string label = 2;</code>
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        label_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.qlcd.qltt.body.pvt.T02007002._req)
    }

    // @@protoc_insertion_point(class_scope:com.qlcd.qltt.body.pvt.T02007002._req)
    private static final com.qlcd.qltt.body.pvt.T02007002._req DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qlcd.qltt.body.pvt.T02007002._req();
    }

    public static com.qlcd.qltt.body.pvt.T02007002._req getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<_req>
        PARSER = new com.google.protobuf.AbstractParser<_req>() {
      public _req parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new _req(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<_req> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<_req> getParserForType() {
      return PARSER;
    }

    public com.qlcd.qltt.body.pvt.T02007002._req getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface _labelstockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qlcd.qltt.body.pvt.T02007002._labelstock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string stockcode = 1;</code>
     */
    java.lang.String getStockcode();
    /**
     * <code>string stockcode = 1;</code>
     */
    com.google.protobuf.ByteString
        getStockcodeBytes();
  }
  /**
   * Protobuf type {@code com.qlcd.qltt.body.pvt.T02007002._labelstock}
   */
  public  static final class _labelstock extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.qlcd.qltt.body.pvt.T02007002._labelstock)
      _labelstockOrBuilder {
    // Use _labelstock.newBuilder() to construct.
    private _labelstock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private _labelstock() {
      stockcode_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private _labelstock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              stockcode_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qlcd.qltt.body.pvt.T02007002.internal_static_com_qlcd_qltt_body_pvt_T02007002__labelstock_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qlcd.qltt.body.pvt.T02007002.internal_static_com_qlcd_qltt_body_pvt_T02007002__labelstock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qlcd.qltt.body.pvt.T02007002._labelstock.class, com.qlcd.qltt.body.pvt.T02007002._labelstock.Builder.class);
    }

    public static final int STOCKCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object stockcode_;
    /**
     * <code>string stockcode = 1;</code>
     */
    public java.lang.String getStockcode() {
      java.lang.Object ref = stockcode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stockcode_ = s;
        return s;
      }
    }
    /**
     * <code>string stockcode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStockcodeBytes() {
      java.lang.Object ref = stockcode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockcode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStockcodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stockcode_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStockcodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stockcode_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qlcd.qltt.body.pvt.T02007002._labelstock)) {
        return super.equals(obj);
      }
      com.qlcd.qltt.body.pvt.T02007002._labelstock other = (com.qlcd.qltt.body.pvt.T02007002._labelstock) obj;

      boolean result = true;
      result = result && getStockcode()
          .equals(other.getStockcode());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STOCKCODE_FIELD_NUMBER;
      hash = (53 * hash) + getStockcode().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qlcd.qltt.body.pvt.T02007002._labelstock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._labelstock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._labelstock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._labelstock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._labelstock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._labelstock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._labelstock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._labelstock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._labelstock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._labelstock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qlcd.qltt.body.pvt.T02007002._labelstock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qlcd.qltt.body.pvt.T02007002._labelstock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qlcd.qltt.body.pvt.T02007002._labelstock)
        com.qlcd.qltt.body.pvt.T02007002._labelstockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qlcd.qltt.body.pvt.T02007002.internal_static_com_qlcd_qltt_body_pvt_T02007002__labelstock_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qlcd.qltt.body.pvt.T02007002.internal_static_com_qlcd_qltt_body_pvt_T02007002__labelstock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qlcd.qltt.body.pvt.T02007002._labelstock.class, com.qlcd.qltt.body.pvt.T02007002._labelstock.Builder.class);
      }

      // Construct using com.qlcd.qltt.body.pvt.T02007002._labelstock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        stockcode_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qlcd.qltt.body.pvt.T02007002.internal_static_com_qlcd_qltt_body_pvt_T02007002__labelstock_descriptor;
      }

      public com.qlcd.qltt.body.pvt.T02007002._labelstock getDefaultInstanceForType() {
        return com.qlcd.qltt.body.pvt.T02007002._labelstock.getDefaultInstance();
      }

      public com.qlcd.qltt.body.pvt.T02007002._labelstock build() {
        com.qlcd.qltt.body.pvt.T02007002._labelstock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qlcd.qltt.body.pvt.T02007002._labelstock buildPartial() {
        com.qlcd.qltt.body.pvt.T02007002._labelstock result = new com.qlcd.qltt.body.pvt.T02007002._labelstock(this);
        result.stockcode_ = stockcode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qlcd.qltt.body.pvt.T02007002._labelstock) {
          return mergeFrom((com.qlcd.qltt.body.pvt.T02007002._labelstock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qlcd.qltt.body.pvt.T02007002._labelstock other) {
        if (other == com.qlcd.qltt.body.pvt.T02007002._labelstock.getDefaultInstance()) return this;
        if (!other.getStockcode().isEmpty()) {
          stockcode_ = other.stockcode_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qlcd.qltt.body.pvt.T02007002._labelstock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qlcd.qltt.body.pvt.T02007002._labelstock) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object stockcode_ = "";
      /**
       * <code>string stockcode = 1;</code>
       */
      public java.lang.String getStockcode() {
        java.lang.Object ref = stockcode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stockcode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stockcode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStockcodeBytes() {
        java.lang.Object ref = stockcode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stockcode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stockcode = 1;</code>
       */
      public Builder setStockcode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stockcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stockcode = 1;</code>
       */
      public Builder clearStockcode() {
        
        stockcode_ = getDefaultInstance().getStockcode();
        onChanged();
        return this;
      }
      /**
       * <code>string stockcode = 1;</code>
       */
      public Builder setStockcodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stockcode_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.qlcd.qltt.body.pvt.T02007002._labelstock)
    }

    // @@protoc_insertion_point(class_scope:com.qlcd.qltt.body.pvt.T02007002._labelstock)
    private static final com.qlcd.qltt.body.pvt.T02007002._labelstock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qlcd.qltt.body.pvt.T02007002._labelstock();
    }

    public static com.qlcd.qltt.body.pvt.T02007002._labelstock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<_labelstock>
        PARSER = new com.google.protobuf.AbstractParser<_labelstock>() {
      public _labelstock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new _labelstock(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<_labelstock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<_labelstock> getParserForType() {
      return PARSER;
    }

    public com.qlcd.qltt.body.pvt.T02007002._labelstock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface _rspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qlcd.qltt.body.pvt.T02007002._rsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    boolean hasRsh();
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    com.qlcd.qltt.body.BppSys._rsp_succhead getRsh();
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder getRshOrBuilder();

    /**
     * <code>.com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
     */
    boolean hasPgrsp();
    /**
     * <code>.com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
     */
    com.qlcd.qltt.body.BppBiz._page_rsp getPgrsp();
    /**
     * <code>.com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
     */
    com.qlcd.qltt.body.BppBiz._page_rspOrBuilder getPgrspOrBuilder();

    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
     */
    java.util.List<com.qlcd.qltt.body.pvt.T02007002._labelstock> 
        getLslistList();
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
     */
    com.qlcd.qltt.body.pvt.T02007002._labelstock getLslist(int index);
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
     */
    int getLslistCount();
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
     */
    java.util.List<? extends com.qlcd.qltt.body.pvt.T02007002._labelstockOrBuilder> 
        getLslistOrBuilderList();
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
     */
    com.qlcd.qltt.body.pvt.T02007002._labelstockOrBuilder getLslistOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.qlcd.qltt.body.pvt.T02007002._rsp}
   */
  public  static final class _rsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.qlcd.qltt.body.pvt.T02007002._rsp)
      _rspOrBuilder {
    // Use _rsp.newBuilder() to construct.
    private _rsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private _rsp() {
      lslist_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private _rsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.qlcd.qltt.body.BppSys._rsp_succhead.Builder subBuilder = null;
              if (rsh_ != null) {
                subBuilder = rsh_.toBuilder();
              }
              rsh_ = input.readMessage(com.qlcd.qltt.body.BppSys._rsp_succhead.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rsh_);
                rsh_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.qlcd.qltt.body.BppBiz._page_rsp.Builder subBuilder = null;
              if (pgrsp_ != null) {
                subBuilder = pgrsp_.toBuilder();
              }
              pgrsp_ = input.readMessage(com.qlcd.qltt.body.BppBiz._page_rsp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pgrsp_);
                pgrsp_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                lslist_ = new java.util.ArrayList<com.qlcd.qltt.body.pvt.T02007002._labelstock>();
                mutable_bitField0_ |= 0x00000004;
              }
              lslist_.add(
                  input.readMessage(com.qlcd.qltt.body.pvt.T02007002._labelstock.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          lslist_ = java.util.Collections.unmodifiableList(lslist_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qlcd.qltt.body.pvt.T02007002.internal_static_com_qlcd_qltt_body_pvt_T02007002__rsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qlcd.qltt.body.pvt.T02007002.internal_static_com_qlcd_qltt_body_pvt_T02007002__rsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qlcd.qltt.body.pvt.T02007002._rsp.class, com.qlcd.qltt.body.pvt.T02007002._rsp.Builder.class);
    }

    private int bitField0_;
    public static final int RSH_FIELD_NUMBER = 1;
    private com.qlcd.qltt.body.BppSys._rsp_succhead rsh_;
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    public boolean hasRsh() {
      return rsh_ != null;
    }
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    public com.qlcd.qltt.body.BppSys._rsp_succhead getRsh() {
      return rsh_ == null ? com.qlcd.qltt.body.BppSys._rsp_succhead.getDefaultInstance() : rsh_;
    }
    /**
     * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    public com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder getRshOrBuilder() {
      return getRsh();
    }

    public static final int PGRSP_FIELD_NUMBER = 2;
    private com.qlcd.qltt.body.BppBiz._page_rsp pgrsp_;
    /**
     * <code>.com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
     */
    public boolean hasPgrsp() {
      return pgrsp_ != null;
    }
    /**
     * <code>.com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
     */
    public com.qlcd.qltt.body.BppBiz._page_rsp getPgrsp() {
      return pgrsp_ == null ? com.qlcd.qltt.body.BppBiz._page_rsp.getDefaultInstance() : pgrsp_;
    }
    /**
     * <code>.com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
     */
    public com.qlcd.qltt.body.BppBiz._page_rspOrBuilder getPgrspOrBuilder() {
      return getPgrsp();
    }

    public static final int LSLIST_FIELD_NUMBER = 3;
    private java.util.List<com.qlcd.qltt.body.pvt.T02007002._labelstock> lslist_;
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
     */
    public java.util.List<com.qlcd.qltt.body.pvt.T02007002._labelstock> getLslistList() {
      return lslist_;
    }
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
     */
    public java.util.List<? extends com.qlcd.qltt.body.pvt.T02007002._labelstockOrBuilder> 
        getLslistOrBuilderList() {
      return lslist_;
    }
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
     */
    public int getLslistCount() {
      return lslist_.size();
    }
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
     */
    public com.qlcd.qltt.body.pvt.T02007002._labelstock getLslist(int index) {
      return lslist_.get(index);
    }
    /**
     * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
     */
    public com.qlcd.qltt.body.pvt.T02007002._labelstockOrBuilder getLslistOrBuilder(
        int index) {
      return lslist_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rsh_ != null) {
        output.writeMessage(1, getRsh());
      }
      if (pgrsp_ != null) {
        output.writeMessage(2, getPgrsp());
      }
      for (int i = 0; i < lslist_.size(); i++) {
        output.writeMessage(3, lslist_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rsh_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRsh());
      }
      if (pgrsp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPgrsp());
      }
      for (int i = 0; i < lslist_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, lslist_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qlcd.qltt.body.pvt.T02007002._rsp)) {
        return super.equals(obj);
      }
      com.qlcd.qltt.body.pvt.T02007002._rsp other = (com.qlcd.qltt.body.pvt.T02007002._rsp) obj;

      boolean result = true;
      result = result && (hasRsh() == other.hasRsh());
      if (hasRsh()) {
        result = result && getRsh()
            .equals(other.getRsh());
      }
      result = result && (hasPgrsp() == other.hasPgrsp());
      if (hasPgrsp()) {
        result = result && getPgrsp()
            .equals(other.getPgrsp());
      }
      result = result && getLslistList()
          .equals(other.getLslistList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRsh()) {
        hash = (37 * hash) + RSH_FIELD_NUMBER;
        hash = (53 * hash) + getRsh().hashCode();
      }
      if (hasPgrsp()) {
        hash = (37 * hash) + PGRSP_FIELD_NUMBER;
        hash = (53 * hash) + getPgrsp().hashCode();
      }
      if (getLslistCount() > 0) {
        hash = (37 * hash) + LSLIST_FIELD_NUMBER;
        hash = (53 * hash) + getLslistList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qlcd.qltt.body.pvt.T02007002._rsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._rsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._rsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._rsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._rsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._rsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._rsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._rsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._rsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qlcd.qltt.body.pvt.T02007002._rsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qlcd.qltt.body.pvt.T02007002._rsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qlcd.qltt.body.pvt.T02007002._rsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qlcd.qltt.body.pvt.T02007002._rsp)
        com.qlcd.qltt.body.pvt.T02007002._rspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qlcd.qltt.body.pvt.T02007002.internal_static_com_qlcd_qltt_body_pvt_T02007002__rsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qlcd.qltt.body.pvt.T02007002.internal_static_com_qlcd_qltt_body_pvt_T02007002__rsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qlcd.qltt.body.pvt.T02007002._rsp.class, com.qlcd.qltt.body.pvt.T02007002._rsp.Builder.class);
      }

      // Construct using com.qlcd.qltt.body.pvt.T02007002._rsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLslistFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (rshBuilder_ == null) {
          rsh_ = null;
        } else {
          rsh_ = null;
          rshBuilder_ = null;
        }
        if (pgrspBuilder_ == null) {
          pgrsp_ = null;
        } else {
          pgrsp_ = null;
          pgrspBuilder_ = null;
        }
        if (lslistBuilder_ == null) {
          lslist_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          lslistBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qlcd.qltt.body.pvt.T02007002.internal_static_com_qlcd_qltt_body_pvt_T02007002__rsp_descriptor;
      }

      public com.qlcd.qltt.body.pvt.T02007002._rsp getDefaultInstanceForType() {
        return com.qlcd.qltt.body.pvt.T02007002._rsp.getDefaultInstance();
      }

      public com.qlcd.qltt.body.pvt.T02007002._rsp build() {
        com.qlcd.qltt.body.pvt.T02007002._rsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qlcd.qltt.body.pvt.T02007002._rsp buildPartial() {
        com.qlcd.qltt.body.pvt.T02007002._rsp result = new com.qlcd.qltt.body.pvt.T02007002._rsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (rshBuilder_ == null) {
          result.rsh_ = rsh_;
        } else {
          result.rsh_ = rshBuilder_.build();
        }
        if (pgrspBuilder_ == null) {
          result.pgrsp_ = pgrsp_;
        } else {
          result.pgrsp_ = pgrspBuilder_.build();
        }
        if (lslistBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            lslist_ = java.util.Collections.unmodifiableList(lslist_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.lslist_ = lslist_;
        } else {
          result.lslist_ = lslistBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qlcd.qltt.body.pvt.T02007002._rsp) {
          return mergeFrom((com.qlcd.qltt.body.pvt.T02007002._rsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qlcd.qltt.body.pvt.T02007002._rsp other) {
        if (other == com.qlcd.qltt.body.pvt.T02007002._rsp.getDefaultInstance()) return this;
        if (other.hasRsh()) {
          mergeRsh(other.getRsh());
        }
        if (other.hasPgrsp()) {
          mergePgrsp(other.getPgrsp());
        }
        if (lslistBuilder_ == null) {
          if (!other.lslist_.isEmpty()) {
            if (lslist_.isEmpty()) {
              lslist_ = other.lslist_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureLslistIsMutable();
              lslist_.addAll(other.lslist_);
            }
            onChanged();
          }
        } else {
          if (!other.lslist_.isEmpty()) {
            if (lslistBuilder_.isEmpty()) {
              lslistBuilder_.dispose();
              lslistBuilder_ = null;
              lslist_ = other.lslist_;
              bitField0_ = (bitField0_ & ~0x00000004);
              lslistBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLslistFieldBuilder() : null;
            } else {
              lslistBuilder_.addAllMessages(other.lslist_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qlcd.qltt.body.pvt.T02007002._rsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qlcd.qltt.body.pvt.T02007002._rsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.qlcd.qltt.body.BppSys._rsp_succhead rsh_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qlcd.qltt.body.BppSys._rsp_succhead, com.qlcd.qltt.body.BppSys._rsp_succhead.Builder, com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder> rshBuilder_;
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public boolean hasRsh() {
        return rshBuilder_ != null || rsh_ != null;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public com.qlcd.qltt.body.BppSys._rsp_succhead getRsh() {
        if (rshBuilder_ == null) {
          return rsh_ == null ? com.qlcd.qltt.body.BppSys._rsp_succhead.getDefaultInstance() : rsh_;
        } else {
          return rshBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder setRsh(com.qlcd.qltt.body.BppSys._rsp_succhead value) {
        if (rshBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rsh_ = value;
          onChanged();
        } else {
          rshBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder setRsh(
          com.qlcd.qltt.body.BppSys._rsp_succhead.Builder builderForValue) {
        if (rshBuilder_ == null) {
          rsh_ = builderForValue.build();
          onChanged();
        } else {
          rshBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder mergeRsh(com.qlcd.qltt.body.BppSys._rsp_succhead value) {
        if (rshBuilder_ == null) {
          if (rsh_ != null) {
            rsh_ =
              com.qlcd.qltt.body.BppSys._rsp_succhead.newBuilder(rsh_).mergeFrom(value).buildPartial();
          } else {
            rsh_ = value;
          }
          onChanged();
        } else {
          rshBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder clearRsh() {
        if (rshBuilder_ == null) {
          rsh_ = null;
          onChanged();
        } else {
          rsh_ = null;
          rshBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public com.qlcd.qltt.body.BppSys._rsp_succhead.Builder getRshBuilder() {
        
        onChanged();
        return getRshFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder getRshOrBuilder() {
        if (rshBuilder_ != null) {
          return rshBuilder_.getMessageOrBuilder();
        } else {
          return rsh_ == null ?
              com.qlcd.qltt.body.BppSys._rsp_succhead.getDefaultInstance() : rsh_;
        }
      }
      /**
       * <code>.com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qlcd.qltt.body.BppSys._rsp_succhead, com.qlcd.qltt.body.BppSys._rsp_succhead.Builder, com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder> 
          getRshFieldBuilder() {
        if (rshBuilder_ == null) {
          rshBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.qlcd.qltt.body.BppSys._rsp_succhead, com.qlcd.qltt.body.BppSys._rsp_succhead.Builder, com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder>(
                  getRsh(),
                  getParentForChildren(),
                  isClean());
          rsh_ = null;
        }
        return rshBuilder_;
      }

      private com.qlcd.qltt.body.BppBiz._page_rsp pgrsp_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qlcd.qltt.body.BppBiz._page_rsp, com.qlcd.qltt.body.BppBiz._page_rsp.Builder, com.qlcd.qltt.body.BppBiz._page_rspOrBuilder> pgrspBuilder_;
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      public boolean hasPgrsp() {
        return pgrspBuilder_ != null || pgrsp_ != null;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      public com.qlcd.qltt.body.BppBiz._page_rsp getPgrsp() {
        if (pgrspBuilder_ == null) {
          return pgrsp_ == null ? com.qlcd.qltt.body.BppBiz._page_rsp.getDefaultInstance() : pgrsp_;
        } else {
          return pgrspBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      public Builder setPgrsp(com.qlcd.qltt.body.BppBiz._page_rsp value) {
        if (pgrspBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pgrsp_ = value;
          onChanged();
        } else {
          pgrspBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      public Builder setPgrsp(
          com.qlcd.qltt.body.BppBiz._page_rsp.Builder builderForValue) {
        if (pgrspBuilder_ == null) {
          pgrsp_ = builderForValue.build();
          onChanged();
        } else {
          pgrspBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      public Builder mergePgrsp(com.qlcd.qltt.body.BppBiz._page_rsp value) {
        if (pgrspBuilder_ == null) {
          if (pgrsp_ != null) {
            pgrsp_ =
              com.qlcd.qltt.body.BppBiz._page_rsp.newBuilder(pgrsp_).mergeFrom(value).buildPartial();
          } else {
            pgrsp_ = value;
          }
          onChanged();
        } else {
          pgrspBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      public Builder clearPgrsp() {
        if (pgrspBuilder_ == null) {
          pgrsp_ = null;
          onChanged();
        } else {
          pgrsp_ = null;
          pgrspBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      public com.qlcd.qltt.body.BppBiz._page_rsp.Builder getPgrspBuilder() {
        
        onChanged();
        return getPgrspFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      public com.qlcd.qltt.body.BppBiz._page_rspOrBuilder getPgrspOrBuilder() {
        if (pgrspBuilder_ != null) {
          return pgrspBuilder_.getMessageOrBuilder();
        } else {
          return pgrsp_ == null ?
              com.qlcd.qltt.body.BppBiz._page_rsp.getDefaultInstance() : pgrsp_;
        }
      }
      /**
       * <code>.com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qlcd.qltt.body.BppBiz._page_rsp, com.qlcd.qltt.body.BppBiz._page_rsp.Builder, com.qlcd.qltt.body.BppBiz._page_rspOrBuilder> 
          getPgrspFieldBuilder() {
        if (pgrspBuilder_ == null) {
          pgrspBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.qlcd.qltt.body.BppBiz._page_rsp, com.qlcd.qltt.body.BppBiz._page_rsp.Builder, com.qlcd.qltt.body.BppBiz._page_rspOrBuilder>(
                  getPgrsp(),
                  getParentForChildren(),
                  isClean());
          pgrsp_ = null;
        }
        return pgrspBuilder_;
      }

      private java.util.List<com.qlcd.qltt.body.pvt.T02007002._labelstock> lslist_ =
        java.util.Collections.emptyList();
      private void ensureLslistIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          lslist_ = new java.util.ArrayList<com.qlcd.qltt.body.pvt.T02007002._labelstock>(lslist_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.qlcd.qltt.body.pvt.T02007002._labelstock, com.qlcd.qltt.body.pvt.T02007002._labelstock.Builder, com.qlcd.qltt.body.pvt.T02007002._labelstockOrBuilder> lslistBuilder_;

      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public java.util.List<com.qlcd.qltt.body.pvt.T02007002._labelstock> getLslistList() {
        if (lslistBuilder_ == null) {
          return java.util.Collections.unmodifiableList(lslist_);
        } else {
          return lslistBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public int getLslistCount() {
        if (lslistBuilder_ == null) {
          return lslist_.size();
        } else {
          return lslistBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public com.qlcd.qltt.body.pvt.T02007002._labelstock getLslist(int index) {
        if (lslistBuilder_ == null) {
          return lslist_.get(index);
        } else {
          return lslistBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public Builder setLslist(
          int index, com.qlcd.qltt.body.pvt.T02007002._labelstock value) {
        if (lslistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLslistIsMutable();
          lslist_.set(index, value);
          onChanged();
        } else {
          lslistBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public Builder setLslist(
          int index, com.qlcd.qltt.body.pvt.T02007002._labelstock.Builder builderForValue) {
        if (lslistBuilder_ == null) {
          ensureLslistIsMutable();
          lslist_.set(index, builderForValue.build());
          onChanged();
        } else {
          lslistBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public Builder addLslist(com.qlcd.qltt.body.pvt.T02007002._labelstock value) {
        if (lslistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLslistIsMutable();
          lslist_.add(value);
          onChanged();
        } else {
          lslistBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public Builder addLslist(
          int index, com.qlcd.qltt.body.pvt.T02007002._labelstock value) {
        if (lslistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLslistIsMutable();
          lslist_.add(index, value);
          onChanged();
        } else {
          lslistBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public Builder addLslist(
          com.qlcd.qltt.body.pvt.T02007002._labelstock.Builder builderForValue) {
        if (lslistBuilder_ == null) {
          ensureLslistIsMutable();
          lslist_.add(builderForValue.build());
          onChanged();
        } else {
          lslistBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public Builder addLslist(
          int index, com.qlcd.qltt.body.pvt.T02007002._labelstock.Builder builderForValue) {
        if (lslistBuilder_ == null) {
          ensureLslistIsMutable();
          lslist_.add(index, builderForValue.build());
          onChanged();
        } else {
          lslistBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public Builder addAllLslist(
          java.lang.Iterable<? extends com.qlcd.qltt.body.pvt.T02007002._labelstock> values) {
        if (lslistBuilder_ == null) {
          ensureLslistIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, lslist_);
          onChanged();
        } else {
          lslistBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public Builder clearLslist() {
        if (lslistBuilder_ == null) {
          lslist_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          lslistBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public Builder removeLslist(int index) {
        if (lslistBuilder_ == null) {
          ensureLslistIsMutable();
          lslist_.remove(index);
          onChanged();
        } else {
          lslistBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public com.qlcd.qltt.body.pvt.T02007002._labelstock.Builder getLslistBuilder(
          int index) {
        return getLslistFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public com.qlcd.qltt.body.pvt.T02007002._labelstockOrBuilder getLslistOrBuilder(
          int index) {
        if (lslistBuilder_ == null) {
          return lslist_.get(index);  } else {
          return lslistBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public java.util.List<? extends com.qlcd.qltt.body.pvt.T02007002._labelstockOrBuilder> 
           getLslistOrBuilderList() {
        if (lslistBuilder_ != null) {
          return lslistBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(lslist_);
        }
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public com.qlcd.qltt.body.pvt.T02007002._labelstock.Builder addLslistBuilder() {
        return getLslistFieldBuilder().addBuilder(
            com.qlcd.qltt.body.pvt.T02007002._labelstock.getDefaultInstance());
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public com.qlcd.qltt.body.pvt.T02007002._labelstock.Builder addLslistBuilder(
          int index) {
        return getLslistFieldBuilder().addBuilder(
            index, com.qlcd.qltt.body.pvt.T02007002._labelstock.getDefaultInstance());
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.pvt.T02007002._labelstock lslist = 3;</code>
       */
      public java.util.List<com.qlcd.qltt.body.pvt.T02007002._labelstock.Builder> 
           getLslistBuilderList() {
        return getLslistFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.qlcd.qltt.body.pvt.T02007002._labelstock, com.qlcd.qltt.body.pvt.T02007002._labelstock.Builder, com.qlcd.qltt.body.pvt.T02007002._labelstockOrBuilder> 
          getLslistFieldBuilder() {
        if (lslistBuilder_ == null) {
          lslistBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.qlcd.qltt.body.pvt.T02007002._labelstock, com.qlcd.qltt.body.pvt.T02007002._labelstock.Builder, com.qlcd.qltt.body.pvt.T02007002._labelstockOrBuilder>(
                  lslist_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          lslist_ = null;
        }
        return lslistBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.qlcd.qltt.body.pvt.T02007002._rsp)
    }

    // @@protoc_insertion_point(class_scope:com.qlcd.qltt.body.pvt.T02007002._rsp)
    private static final com.qlcd.qltt.body.pvt.T02007002._rsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qlcd.qltt.body.pvt.T02007002._rsp();
    }

    public static com.qlcd.qltt.body.pvt.T02007002._rsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<_rsp>
        PARSER = new com.google.protobuf.AbstractParser<_rsp>() {
      public _rsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new _rsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<_rsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<_rsp> getParserForType() {
      return PARSER;
    }

    public com.qlcd.qltt.body.pvt.T02007002._rsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qlcd_qltt_body_pvt_T02007002__req_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_qlcd_qltt_body_pvt_T02007002__req_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qlcd_qltt_body_pvt_T02007002__labelstock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_qlcd_qltt_body_pvt_T02007002__labelstock_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qlcd_qltt_body_pvt_T02007002__rsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_qlcd_qltt_body_pvt_T02007002__rsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030body/pvt/T02007002.proto\022 com.qlcd.qlt" +
      "t.body.pvt.T02007002\032\021body/BppSys.proto\032" +
      "\021body/BppBiz.proto\"J\n\004_req\0223\n\005pgreq\030\001 \001(" +
      "\0132$.com.qlcd.qltt.body.BppBiz._page_req\022" +
      "\r\n\005label\030\002 \001(\t\" \n\013_labelstock\022\021\n\tstockco" +
      "de\030\001 \001(\t\"\261\001\n\004_rsp\0225\n\003rsh\030\001 \001(\0132(.com.qlc" +
      "d.qltt.body.BppSys._rsp_succhead\0223\n\005pgrs" +
      "p\030\002 \001(\0132$.com.qlcd.qltt.body.BppBiz._pag" +
      "e_rsp\022=\n\006lslist\030\003 \003(\0132-.com.qlcd.qltt.bo" +
      "dy.pvt.T02007002._labelstockB\030\n\026com.qlcd",
      ".qltt.body.pvtb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.qlcd.qltt.body.BppSys.getDescriptor(),
          com.qlcd.qltt.body.BppBiz.getDescriptor(),
        }, assigner);
    internal_static_com_qlcd_qltt_body_pvt_T02007002__req_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_qlcd_qltt_body_pvt_T02007002__req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_qlcd_qltt_body_pvt_T02007002__req_descriptor,
        new java.lang.String[] { "Pgreq", "Label", });
    internal_static_com_qlcd_qltt_body_pvt_T02007002__labelstock_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_qlcd_qltt_body_pvt_T02007002__labelstock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_qlcd_qltt_body_pvt_T02007002__labelstock_descriptor,
        new java.lang.String[] { "Stockcode", });
    internal_static_com_qlcd_qltt_body_pvt_T02007002__rsp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_qlcd_qltt_body_pvt_T02007002__rsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_qlcd_qltt_body_pvt_T02007002__rsp_descriptor,
        new java.lang.String[] { "Rsh", "Pgrsp", "Lslist", });
    com.qlcd.qltt.body.BppSys.getDescriptor();
    com.qlcd.qltt.body.BppBiz.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
