// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prt/T02003001.proto

package com.qlcd.qltt.body.prt;

public final class T02003001 {
  private T02003001() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface _reqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qlcd.qltt.body.prt.T02003001._req)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
     */
    boolean hasPgreq();
    /**
     * <code>optional .com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
     */
    com.qlcd.qltt.body.BppBiz._page_req getPgreq();
    /**
     * <code>optional .com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
     */
    com.qlcd.qltt.body.BppBiz._page_reqOrBuilder getPgreqOrBuilder();

    /**
     * <code>optional string tactic = 2;</code>
     */
    java.lang.String getTactic();
    /**
     * <code>optional string tactic = 2;</code>
     */
    com.google.protobuf.ByteString
        getTacticBytes();

    /**
     * <code>optional int32 tacprm = 3;</code>
     */
    int getTacprm();
  }
  /**
   * Protobuf type {@code com.qlcd.qltt.body.prt.T02003001._req}
   */
  public  static final class _req extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.qlcd.qltt.body.prt.T02003001._req)
      _reqOrBuilder {
    // Use _req.newBuilder() to construct.
    private _req(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private _req() {
      tactic_ = "";
      tacprm_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private _req(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.qlcd.qltt.body.BppBiz._page_req.Builder subBuilder = null;
              if (pgreq_ != null) {
                subBuilder = pgreq_.toBuilder();
              }
              pgreq_ = input.readMessage(com.qlcd.qltt.body.BppBiz._page_req.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pgreq_);
                pgreq_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();

              tactic_ = bs;
              break;
            }
            case 24: {

              tacprm_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qlcd.qltt.body.prt.T02003001.internal_static_com_qlcd_qltt_body_prt_T02003001__req_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qlcd.qltt.body.prt.T02003001.internal_static_com_qlcd_qltt_body_prt_T02003001__req_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qlcd.qltt.body.prt.T02003001._req.class, com.qlcd.qltt.body.prt.T02003001._req.Builder.class);
    }

    public static final com.google.protobuf.Parser<_req> PARSER =
        new com.google.protobuf.AbstractParser<_req>() {
      public _req parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new _req(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<_req> getParserForType() {
      return PARSER;
    }

    public static final int PGREQ_FIELD_NUMBER = 1;
    private com.qlcd.qltt.body.BppBiz._page_req pgreq_;
    /**
     * <code>optional .com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
     */
    public boolean hasPgreq() {
      return pgreq_ != null;
    }
    /**
     * <code>optional .com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
     */
    public com.qlcd.qltt.body.BppBiz._page_req getPgreq() {
      return pgreq_ == null ? com.qlcd.qltt.body.BppBiz._page_req.getDefaultInstance() : pgreq_;
    }
    /**
     * <code>optional .com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
     */
    public com.qlcd.qltt.body.BppBiz._page_reqOrBuilder getPgreqOrBuilder() {
      return getPgreq();
    }

    public static final int TACTIC_FIELD_NUMBER = 2;
    private java.lang.Object tactic_;
    /**
     * <code>optional string tactic = 2;</code>
     */
    public java.lang.String getTactic() {
      java.lang.Object ref = tactic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tactic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tactic = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTacticBytes() {
      java.lang.Object ref = tactic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tactic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TACPRM_FIELD_NUMBER = 3;
    private int tacprm_;
    /**
     * <code>optional int32 tacprm = 3;</code>
     */
    public int getTacprm() {
      return tacprm_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (pgreq_ != null) {
        output.writeMessage(1, getPgreq());
      }
      if (!getTacticBytes().isEmpty()) {
        output.writeBytes(2, getTacticBytes());
      }
      if (tacprm_ != 0) {
        output.writeInt32(3, tacprm_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (pgreq_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPgreq());
      }
      if (!getTacticBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTacticBytes());
      }
      if (tacprm_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, tacprm_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.qlcd.qltt.body.prt.T02003001._req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.prt.T02003001._req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.prt.T02003001._req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.prt.T02003001._req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.prt.T02003001._req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qlcd.qltt.body.prt.T02003001._req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.prt.T02003001._req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qlcd.qltt.body.prt.T02003001._req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.prt.T02003001._req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qlcd.qltt.body.prt.T02003001._req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qlcd.qltt.body.prt.T02003001._req prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qlcd.qltt.body.prt.T02003001._req}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qlcd.qltt.body.prt.T02003001._req)
        com.qlcd.qltt.body.prt.T02003001._reqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qlcd.qltt.body.prt.T02003001.internal_static_com_qlcd_qltt_body_prt_T02003001__req_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qlcd.qltt.body.prt.T02003001.internal_static_com_qlcd_qltt_body_prt_T02003001__req_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qlcd.qltt.body.prt.T02003001._req.class, com.qlcd.qltt.body.prt.T02003001._req.Builder.class);
      }

      // Construct using com.qlcd.qltt.body.prt.T02003001._req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (pgreqBuilder_ == null) {
          pgreq_ = null;
        } else {
          pgreq_ = null;
          pgreqBuilder_ = null;
        }
        tactic_ = "";

        tacprm_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qlcd.qltt.body.prt.T02003001.internal_static_com_qlcd_qltt_body_prt_T02003001__req_descriptor;
      }

      public com.qlcd.qltt.body.prt.T02003001._req getDefaultInstanceForType() {
        return com.qlcd.qltt.body.prt.T02003001._req.getDefaultInstance();
      }

      public com.qlcd.qltt.body.prt.T02003001._req build() {
        com.qlcd.qltt.body.prt.T02003001._req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qlcd.qltt.body.prt.T02003001._req buildPartial() {
        com.qlcd.qltt.body.prt.T02003001._req result = new com.qlcd.qltt.body.prt.T02003001._req(this);
        if (pgreqBuilder_ == null) {
          result.pgreq_ = pgreq_;
        } else {
          result.pgreq_ = pgreqBuilder_.build();
        }
        result.tactic_ = tactic_;
        result.tacprm_ = tacprm_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qlcd.qltt.body.prt.T02003001._req) {
          return mergeFrom((com.qlcd.qltt.body.prt.T02003001._req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qlcd.qltt.body.prt.T02003001._req other) {
        if (other == com.qlcd.qltt.body.prt.T02003001._req.getDefaultInstance()) return this;
        if (other.hasPgreq()) {
          mergePgreq(other.getPgreq());
        }
        if (!other.getTactic().isEmpty()) {
          tactic_ = other.tactic_;
          onChanged();
        }
        if (other.getTacprm() != 0) {
          setTacprm(other.getTacprm());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qlcd.qltt.body.prt.T02003001._req parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qlcd.qltt.body.prt.T02003001._req) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.qlcd.qltt.body.BppBiz._page_req pgreq_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.qlcd.qltt.body.BppBiz._page_req, com.qlcd.qltt.body.BppBiz._page_req.Builder, com.qlcd.qltt.body.BppBiz._page_reqOrBuilder> pgreqBuilder_;
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      public boolean hasPgreq() {
        return pgreqBuilder_ != null || pgreq_ != null;
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      public com.qlcd.qltt.body.BppBiz._page_req getPgreq() {
        if (pgreqBuilder_ == null) {
          return pgreq_ == null ? com.qlcd.qltt.body.BppBiz._page_req.getDefaultInstance() : pgreq_;
        } else {
          return pgreqBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      public Builder setPgreq(com.qlcd.qltt.body.BppBiz._page_req value) {
        if (pgreqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pgreq_ = value;
          onChanged();
        } else {
          pgreqBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      public Builder setPgreq(
          com.qlcd.qltt.body.BppBiz._page_req.Builder builderForValue) {
        if (pgreqBuilder_ == null) {
          pgreq_ = builderForValue.build();
          onChanged();
        } else {
          pgreqBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      public Builder mergePgreq(com.qlcd.qltt.body.BppBiz._page_req value) {
        if (pgreqBuilder_ == null) {
          if (pgreq_ != null) {
            pgreq_ =
              com.qlcd.qltt.body.BppBiz._page_req.newBuilder(pgreq_).mergeFrom(value).buildPartial();
          } else {
            pgreq_ = value;
          }
          onChanged();
        } else {
          pgreqBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      public Builder clearPgreq() {
        if (pgreqBuilder_ == null) {
          pgreq_ = null;
          onChanged();
        } else {
          pgreq_ = null;
          pgreqBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      public com.qlcd.qltt.body.BppBiz._page_req.Builder getPgreqBuilder() {
        
        onChanged();
        return getPgreqFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      public com.qlcd.qltt.body.BppBiz._page_reqOrBuilder getPgreqOrBuilder() {
        if (pgreqBuilder_ != null) {
          return pgreqBuilder_.getMessageOrBuilder();
        } else {
          return pgreq_ == null ?
              com.qlcd.qltt.body.BppBiz._page_req.getDefaultInstance() : pgreq_;
        }
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_req pgreq = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.qlcd.qltt.body.BppBiz._page_req, com.qlcd.qltt.body.BppBiz._page_req.Builder, com.qlcd.qltt.body.BppBiz._page_reqOrBuilder> 
          getPgreqFieldBuilder() {
        if (pgreqBuilder_ == null) {
          pgreqBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.qlcd.qltt.body.BppBiz._page_req, com.qlcd.qltt.body.BppBiz._page_req.Builder, com.qlcd.qltt.body.BppBiz._page_reqOrBuilder>(
                  getPgreq(),
                  getParentForChildren(),
                  isClean());
          pgreq_ = null;
        }
        return pgreqBuilder_;
      }

      private java.lang.Object tactic_ = "";
      /**
       * <code>optional string tactic = 2;</code>
       */
      public java.lang.String getTactic() {
        java.lang.Object ref = tactic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tactic_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tactic = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTacticBytes() {
        java.lang.Object ref = tactic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tactic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tactic = 2;</code>
       */
      public Builder setTactic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tactic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tactic = 2;</code>
       */
      public Builder clearTactic() {
        
        tactic_ = getDefaultInstance().getTactic();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tactic = 2;</code>
       */
      public Builder setTacticBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tactic_ = value;
        onChanged();
        return this;
      }

      private int tacprm_ ;
      /**
       * <code>optional int32 tacprm = 3;</code>
       */
      public int getTacprm() {
        return tacprm_;
      }
      /**
       * <code>optional int32 tacprm = 3;</code>
       */
      public Builder setTacprm(int value) {
        
        tacprm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 tacprm = 3;</code>
       */
      public Builder clearTacprm() {
        
        tacprm_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.qlcd.qltt.body.prt.T02003001._req)
    }

    // @@protoc_insertion_point(class_scope:com.qlcd.qltt.body.prt.T02003001._req)
    private static final com.qlcd.qltt.body.prt.T02003001._req defaultInstance;static {
      defaultInstance = new com.qlcd.qltt.body.prt.T02003001._req();
    }

    public static com.qlcd.qltt.body.prt.T02003001._req getDefaultInstance() {
      return defaultInstance;
    }

    public com.qlcd.qltt.body.prt.T02003001._req getDefaultInstanceForType() {
      return defaultInstance;
    }

  }

  public interface _dprealtimeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qlcd.qltt.body.prt.T02003001._dprealtime)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string tactic = 1;</code>
     */
    java.lang.String getTactic();
    /**
     * <code>optional string tactic = 1;</code>
     */
    com.google.protobuf.ByteString
        getTacticBytes();

    /**
     * <code>optional int32 tacprm = 2;</code>
     */
    int getTacprm();

    /**
     * <code>optional int32 index = 3;</code>
     */
    int getIndex();

    /**
     * <code>optional string stockcode = 4;</code>
     */
    java.lang.String getStockcode();
    /**
     * <code>optional string stockcode = 4;</code>
     */
    com.google.protobuf.ByteString
        getStockcodeBytes();

    /**
     * <code>optional string occval = 5;</code>
     */
    java.lang.String getOccval();
    /**
     * <code>optional string occval = 5;</code>
     */
    com.google.protobuf.ByteString
        getOccvalBytes();

    /**
     * <code>optional string remarks = 6;</code>
     */
    java.lang.String getRemarks();
    /**
     * <code>optional string remarks = 6;</code>
     */
    com.google.protobuf.ByteString
        getRemarksBytes();

    /**
     * <code>optional string efftime = 7;</code>
     */
    java.lang.String getEfftime();
    /**
     * <code>optional string efftime = 7;</code>
     */
    com.google.protobuf.ByteString
        getEfftimeBytes();

    /**
     * <code>optional int32 count = 8;</code>
     */
    int getCount();
  }
  /**
   * Protobuf type {@code com.qlcd.qltt.body.prt.T02003001._dprealtime}
   */
  public  static final class _dprealtime extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.qlcd.qltt.body.prt.T02003001._dprealtime)
      _dprealtimeOrBuilder {
    // Use _dprealtime.newBuilder() to construct.
    private _dprealtime(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private _dprealtime() {
      tactic_ = "";
      tacprm_ = 0;
      index_ = 0;
      stockcode_ = "";
      occval_ = "";
      remarks_ = "";
      efftime_ = "";
      count_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private _dprealtime(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();

              tactic_ = bs;
              break;
            }
            case 16: {

              tacprm_ = input.readInt32();
              break;
            }
            case 24: {

              index_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();

              stockcode_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();

              occval_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();

              remarks_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();

              efftime_ = bs;
              break;
            }
            case 64: {

              count_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qlcd.qltt.body.prt.T02003001.internal_static_com_qlcd_qltt_body_prt_T02003001__dprealtime_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qlcd.qltt.body.prt.T02003001.internal_static_com_qlcd_qltt_body_prt_T02003001__dprealtime_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qlcd.qltt.body.prt.T02003001._dprealtime.class, com.qlcd.qltt.body.prt.T02003001._dprealtime.Builder.class);
    }

    public static final com.google.protobuf.Parser<_dprealtime> PARSER =
        new com.google.protobuf.AbstractParser<_dprealtime>() {
      public _dprealtime parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new _dprealtime(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<_dprealtime> getParserForType() {
      return PARSER;
    }

    public static final int TACTIC_FIELD_NUMBER = 1;
    private java.lang.Object tactic_;
    /**
     * <code>optional string tactic = 1;</code>
     */
    public java.lang.String getTactic() {
      java.lang.Object ref = tactic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tactic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tactic = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTacticBytes() {
      java.lang.Object ref = tactic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tactic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TACPRM_FIELD_NUMBER = 2;
    private int tacprm_;
    /**
     * <code>optional int32 tacprm = 2;</code>
     */
    public int getTacprm() {
      return tacprm_;
    }

    public static final int INDEX_FIELD_NUMBER = 3;
    private int index_;
    /**
     * <code>optional int32 index = 3;</code>
     */
    public int getIndex() {
      return index_;
    }

    public static final int STOCKCODE_FIELD_NUMBER = 4;
    private java.lang.Object stockcode_;
    /**
     * <code>optional string stockcode = 4;</code>
     */
    public java.lang.String getStockcode() {
      java.lang.Object ref = stockcode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stockcode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stockcode = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStockcodeBytes() {
      java.lang.Object ref = stockcode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockcode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OCCVAL_FIELD_NUMBER = 5;
    private java.lang.Object occval_;
    /**
     * <code>optional string occval = 5;</code>
     */
    public java.lang.String getOccval() {
      java.lang.Object ref = occval_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          occval_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string occval = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOccvalBytes() {
      java.lang.Object ref = occval_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        occval_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMARKS_FIELD_NUMBER = 6;
    private java.lang.Object remarks_;
    /**
     * <code>optional string remarks = 6;</code>
     */
    public java.lang.String getRemarks() {
      java.lang.Object ref = remarks_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          remarks_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string remarks = 6;</code>
     */
    public com.google.protobuf.ByteString
        getRemarksBytes() {
      java.lang.Object ref = remarks_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remarks_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EFFTIME_FIELD_NUMBER = 7;
    private java.lang.Object efftime_;
    /**
     * <code>optional string efftime = 7;</code>
     */
    public java.lang.String getEfftime() {
      java.lang.Object ref = efftime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          efftime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string efftime = 7;</code>
     */
    public com.google.protobuf.ByteString
        getEfftimeBytes() {
      java.lang.Object ref = efftime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        efftime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNT_FIELD_NUMBER = 8;
    private int count_;
    /**
     * <code>optional int32 count = 8;</code>
     */
    public int getCount() {
      return count_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getTacticBytes().isEmpty()) {
        output.writeBytes(1, getTacticBytes());
      }
      if (tacprm_ != 0) {
        output.writeInt32(2, tacprm_);
      }
      if (index_ != 0) {
        output.writeInt32(3, index_);
      }
      if (!getStockcodeBytes().isEmpty()) {
        output.writeBytes(4, getStockcodeBytes());
      }
      if (!getOccvalBytes().isEmpty()) {
        output.writeBytes(5, getOccvalBytes());
      }
      if (!getRemarksBytes().isEmpty()) {
        output.writeBytes(6, getRemarksBytes());
      }
      if (!getEfftimeBytes().isEmpty()) {
        output.writeBytes(7, getEfftimeBytes());
      }
      if (count_ != 0) {
        output.writeInt32(8, count_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTacticBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTacticBytes());
      }
      if (tacprm_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, tacprm_);
      }
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, index_);
      }
      if (!getStockcodeBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getStockcodeBytes());
      }
      if (!getOccvalBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getOccvalBytes());
      }
      if (!getRemarksBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getRemarksBytes());
      }
      if (!getEfftimeBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getEfftimeBytes());
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, count_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.qlcd.qltt.body.prt.T02003001._dprealtime parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.prt.T02003001._dprealtime parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.prt.T02003001._dprealtime parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.prt.T02003001._dprealtime parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.prt.T02003001._dprealtime parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qlcd.qltt.body.prt.T02003001._dprealtime parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.prt.T02003001._dprealtime parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qlcd.qltt.body.prt.T02003001._dprealtime parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.prt.T02003001._dprealtime parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qlcd.qltt.body.prt.T02003001._dprealtime parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qlcd.qltt.body.prt.T02003001._dprealtime prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qlcd.qltt.body.prt.T02003001._dprealtime}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qlcd.qltt.body.prt.T02003001._dprealtime)
        com.qlcd.qltt.body.prt.T02003001._dprealtimeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qlcd.qltt.body.prt.T02003001.internal_static_com_qlcd_qltt_body_prt_T02003001__dprealtime_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qlcd.qltt.body.prt.T02003001.internal_static_com_qlcd_qltt_body_prt_T02003001__dprealtime_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qlcd.qltt.body.prt.T02003001._dprealtime.class, com.qlcd.qltt.body.prt.T02003001._dprealtime.Builder.class);
      }

      // Construct using com.qlcd.qltt.body.prt.T02003001._dprealtime.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        tactic_ = "";

        tacprm_ = 0;

        index_ = 0;

        stockcode_ = "";

        occval_ = "";

        remarks_ = "";

        efftime_ = "";

        count_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qlcd.qltt.body.prt.T02003001.internal_static_com_qlcd_qltt_body_prt_T02003001__dprealtime_descriptor;
      }

      public com.qlcd.qltt.body.prt.T02003001._dprealtime getDefaultInstanceForType() {
        return com.qlcd.qltt.body.prt.T02003001._dprealtime.getDefaultInstance();
      }

      public com.qlcd.qltt.body.prt.T02003001._dprealtime build() {
        com.qlcd.qltt.body.prt.T02003001._dprealtime result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qlcd.qltt.body.prt.T02003001._dprealtime buildPartial() {
        com.qlcd.qltt.body.prt.T02003001._dprealtime result = new com.qlcd.qltt.body.prt.T02003001._dprealtime(this);
        result.tactic_ = tactic_;
        result.tacprm_ = tacprm_;
        result.index_ = index_;
        result.stockcode_ = stockcode_;
        result.occval_ = occval_;
        result.remarks_ = remarks_;
        result.efftime_ = efftime_;
        result.count_ = count_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qlcd.qltt.body.prt.T02003001._dprealtime) {
          return mergeFrom((com.qlcd.qltt.body.prt.T02003001._dprealtime)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qlcd.qltt.body.prt.T02003001._dprealtime other) {
        if (other == com.qlcd.qltt.body.prt.T02003001._dprealtime.getDefaultInstance()) return this;
        if (!other.getTactic().isEmpty()) {
          tactic_ = other.tactic_;
          onChanged();
        }
        if (other.getTacprm() != 0) {
          setTacprm(other.getTacprm());
        }
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        if (!other.getStockcode().isEmpty()) {
          stockcode_ = other.stockcode_;
          onChanged();
        }
        if (!other.getOccval().isEmpty()) {
          occval_ = other.occval_;
          onChanged();
        }
        if (!other.getRemarks().isEmpty()) {
          remarks_ = other.remarks_;
          onChanged();
        }
        if (!other.getEfftime().isEmpty()) {
          efftime_ = other.efftime_;
          onChanged();
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qlcd.qltt.body.prt.T02003001._dprealtime parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qlcd.qltt.body.prt.T02003001._dprealtime) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object tactic_ = "";
      /**
       * <code>optional string tactic = 1;</code>
       */
      public java.lang.String getTactic() {
        java.lang.Object ref = tactic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tactic_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tactic = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTacticBytes() {
        java.lang.Object ref = tactic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tactic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tactic = 1;</code>
       */
      public Builder setTactic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tactic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tactic = 1;</code>
       */
      public Builder clearTactic() {
        
        tactic_ = getDefaultInstance().getTactic();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tactic = 1;</code>
       */
      public Builder setTacticBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tactic_ = value;
        onChanged();
        return this;
      }

      private int tacprm_ ;
      /**
       * <code>optional int32 tacprm = 2;</code>
       */
      public int getTacprm() {
        return tacprm_;
      }
      /**
       * <code>optional int32 tacprm = 2;</code>
       */
      public Builder setTacprm(int value) {
        
        tacprm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 tacprm = 2;</code>
       */
      public Builder clearTacprm() {
        
        tacprm_ = 0;
        onChanged();
        return this;
      }

      private int index_ ;
      /**
       * <code>optional int32 index = 3;</code>
       */
      public int getIndex() {
        return index_;
      }
      /**
       * <code>optional int32 index = 3;</code>
       */
      public Builder setIndex(int value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 index = 3;</code>
       */
      public Builder clearIndex() {
        
        index_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object stockcode_ = "";
      /**
       * <code>optional string stockcode = 4;</code>
       */
      public java.lang.String getStockcode() {
        java.lang.Object ref = stockcode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stockcode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stockcode = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStockcodeBytes() {
        java.lang.Object ref = stockcode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stockcode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stockcode = 4;</code>
       */
      public Builder setStockcode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stockcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stockcode = 4;</code>
       */
      public Builder clearStockcode() {
        
        stockcode_ = getDefaultInstance().getStockcode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string stockcode = 4;</code>
       */
      public Builder setStockcodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stockcode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object occval_ = "";
      /**
       * <code>optional string occval = 5;</code>
       */
      public java.lang.String getOccval() {
        java.lang.Object ref = occval_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            occval_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string occval = 5;</code>
       */
      public com.google.protobuf.ByteString
          getOccvalBytes() {
        java.lang.Object ref = occval_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          occval_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string occval = 5;</code>
       */
      public Builder setOccval(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        occval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string occval = 5;</code>
       */
      public Builder clearOccval() {
        
        occval_ = getDefaultInstance().getOccval();
        onChanged();
        return this;
      }
      /**
       * <code>optional string occval = 5;</code>
       */
      public Builder setOccvalBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        occval_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object remarks_ = "";
      /**
       * <code>optional string remarks = 6;</code>
       */
      public java.lang.String getRemarks() {
        java.lang.Object ref = remarks_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            remarks_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string remarks = 6;</code>
       */
      public com.google.protobuf.ByteString
          getRemarksBytes() {
        java.lang.Object ref = remarks_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remarks_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string remarks = 6;</code>
       */
      public Builder setRemarks(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remarks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string remarks = 6;</code>
       */
      public Builder clearRemarks() {
        
        remarks_ = getDefaultInstance().getRemarks();
        onChanged();
        return this;
      }
      /**
       * <code>optional string remarks = 6;</code>
       */
      public Builder setRemarksBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remarks_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object efftime_ = "";
      /**
       * <code>optional string efftime = 7;</code>
       */
      public java.lang.String getEfftime() {
        java.lang.Object ref = efftime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            efftime_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string efftime = 7;</code>
       */
      public com.google.protobuf.ByteString
          getEfftimeBytes() {
        java.lang.Object ref = efftime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          efftime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string efftime = 7;</code>
       */
      public Builder setEfftime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        efftime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string efftime = 7;</code>
       */
      public Builder clearEfftime() {
        
        efftime_ = getDefaultInstance().getEfftime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string efftime = 7;</code>
       */
      public Builder setEfftimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        efftime_ = value;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>optional int32 count = 8;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional int32 count = 8;</code>
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 count = 8;</code>
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.qlcd.qltt.body.prt.T02003001._dprealtime)
    }

    // @@protoc_insertion_point(class_scope:com.qlcd.qltt.body.prt.T02003001._dprealtime)
    private static final com.qlcd.qltt.body.prt.T02003001._dprealtime defaultInstance;static {
      defaultInstance = new com.qlcd.qltt.body.prt.T02003001._dprealtime();
    }

    public static com.qlcd.qltt.body.prt.T02003001._dprealtime getDefaultInstance() {
      return defaultInstance;
    }

    public com.qlcd.qltt.body.prt.T02003001._dprealtime getDefaultInstanceForType() {
      return defaultInstance;
    }

  }

  public interface _rspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qlcd.qltt.body.prt.T02003001._rsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    boolean hasRsh();
    /**
     * <code>optional .com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    com.qlcd.qltt.body.BppSys._rsp_succhead getRsh();
    /**
     * <code>optional .com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder getRshOrBuilder();

    /**
     * <code>optional .com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
     */
    boolean hasPgrsp();
    /**
     * <code>optional .com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
     */
    com.qlcd.qltt.body.BppBiz._page_rsp getPgrsp();
    /**
     * <code>optional .com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
     */
    com.qlcd.qltt.body.BppBiz._page_rspOrBuilder getPgrspOrBuilder();

    /**
     * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
     */
    java.util.List<com.qlcd.qltt.body.prt.T02003001._dprealtime> 
        getDprtlistList();
    /**
     * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
     */
    com.qlcd.qltt.body.prt.T02003001._dprealtime getDprtlist(int index);
    /**
     * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
     */
    int getDprtlistCount();
    /**
     * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
     */
    java.util.List<? extends com.qlcd.qltt.body.prt.T02003001._dprealtimeOrBuilder> 
        getDprtlistOrBuilderList();
    /**
     * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
     */
    com.qlcd.qltt.body.prt.T02003001._dprealtimeOrBuilder getDprtlistOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.qlcd.qltt.body.prt.T02003001._rsp}
   */
  public  static final class _rsp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.qlcd.qltt.body.prt.T02003001._rsp)
      _rspOrBuilder {
    // Use _rsp.newBuilder() to construct.
    private _rsp(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private _rsp() {
      dprtlist_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private _rsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.qlcd.qltt.body.BppSys._rsp_succhead.Builder subBuilder = null;
              if (rsh_ != null) {
                subBuilder = rsh_.toBuilder();
              }
              rsh_ = input.readMessage(com.qlcd.qltt.body.BppSys._rsp_succhead.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rsh_);
                rsh_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.qlcd.qltt.body.BppBiz._page_rsp.Builder subBuilder = null;
              if (pgrsp_ != null) {
                subBuilder = pgrsp_.toBuilder();
              }
              pgrsp_ = input.readMessage(com.qlcd.qltt.body.BppBiz._page_rsp.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pgrsp_);
                pgrsp_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                dprtlist_ = new java.util.ArrayList<com.qlcd.qltt.body.prt.T02003001._dprealtime>();
                mutable_bitField0_ |= 0x00000004;
              }
              dprtlist_.add(input.readMessage(com.qlcd.qltt.body.prt.T02003001._dprealtime.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          dprtlist_ = java.util.Collections.unmodifiableList(dprtlist_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qlcd.qltt.body.prt.T02003001.internal_static_com_qlcd_qltt_body_prt_T02003001__rsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qlcd.qltt.body.prt.T02003001.internal_static_com_qlcd_qltt_body_prt_T02003001__rsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qlcd.qltt.body.prt.T02003001._rsp.class, com.qlcd.qltt.body.prt.T02003001._rsp.Builder.class);
    }

    public static final com.google.protobuf.Parser<_rsp> PARSER =
        new com.google.protobuf.AbstractParser<_rsp>() {
      public _rsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new _rsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<_rsp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RSH_FIELD_NUMBER = 1;
    private com.qlcd.qltt.body.BppSys._rsp_succhead rsh_;
    /**
     * <code>optional .com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    public boolean hasRsh() {
      return rsh_ != null;
    }
    /**
     * <code>optional .com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    public com.qlcd.qltt.body.BppSys._rsp_succhead getRsh() {
      return rsh_ == null ? com.qlcd.qltt.body.BppSys._rsp_succhead.getDefaultInstance() : rsh_;
    }
    /**
     * <code>optional .com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
     */
    public com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder getRshOrBuilder() {
      return getRsh();
    }

    public static final int PGRSP_FIELD_NUMBER = 2;
    private com.qlcd.qltt.body.BppBiz._page_rsp pgrsp_;
    /**
     * <code>optional .com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
     */
    public boolean hasPgrsp() {
      return pgrsp_ != null;
    }
    /**
     * <code>optional .com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
     */
    public com.qlcd.qltt.body.BppBiz._page_rsp getPgrsp() {
      return pgrsp_ == null ? com.qlcd.qltt.body.BppBiz._page_rsp.getDefaultInstance() : pgrsp_;
    }
    /**
     * <code>optional .com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
     */
    public com.qlcd.qltt.body.BppBiz._page_rspOrBuilder getPgrspOrBuilder() {
      return getPgrsp();
    }

    public static final int DPRTLIST_FIELD_NUMBER = 3;
    private java.util.List<com.qlcd.qltt.body.prt.T02003001._dprealtime> dprtlist_;
    /**
     * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
     */
    public java.util.List<com.qlcd.qltt.body.prt.T02003001._dprealtime> getDprtlistList() {
      return dprtlist_;
    }
    /**
     * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
     */
    public java.util.List<? extends com.qlcd.qltt.body.prt.T02003001._dprealtimeOrBuilder> 
        getDprtlistOrBuilderList() {
      return dprtlist_;
    }
    /**
     * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
     */
    public int getDprtlistCount() {
      return dprtlist_.size();
    }
    /**
     * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
     */
    public com.qlcd.qltt.body.prt.T02003001._dprealtime getDprtlist(int index) {
      return dprtlist_.get(index);
    }
    /**
     * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
     */
    public com.qlcd.qltt.body.prt.T02003001._dprealtimeOrBuilder getDprtlistOrBuilder(
        int index) {
      return dprtlist_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (rsh_ != null) {
        output.writeMessage(1, getRsh());
      }
      if (pgrsp_ != null) {
        output.writeMessage(2, getPgrsp());
      }
      for (int i = 0; i < dprtlist_.size(); i++) {
        output.writeMessage(3, dprtlist_.get(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (rsh_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRsh());
      }
      if (pgrsp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPgrsp());
      }
      for (int i = 0; i < dprtlist_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, dprtlist_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.qlcd.qltt.body.prt.T02003001._rsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.prt.T02003001._rsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.prt.T02003001._rsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qlcd.qltt.body.prt.T02003001._rsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qlcd.qltt.body.prt.T02003001._rsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qlcd.qltt.body.prt.T02003001._rsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.prt.T02003001._rsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qlcd.qltt.body.prt.T02003001._rsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qlcd.qltt.body.prt.T02003001._rsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qlcd.qltt.body.prt.T02003001._rsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qlcd.qltt.body.prt.T02003001._rsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qlcd.qltt.body.prt.T02003001._rsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qlcd.qltt.body.prt.T02003001._rsp)
        com.qlcd.qltt.body.prt.T02003001._rspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qlcd.qltt.body.prt.T02003001.internal_static_com_qlcd_qltt_body_prt_T02003001__rsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qlcd.qltt.body.prt.T02003001.internal_static_com_qlcd_qltt_body_prt_T02003001__rsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qlcd.qltt.body.prt.T02003001._rsp.class, com.qlcd.qltt.body.prt.T02003001._rsp.Builder.class);
      }

      // Construct using com.qlcd.qltt.body.prt.T02003001._rsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDprtlistFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (rshBuilder_ == null) {
          rsh_ = null;
        } else {
          rsh_ = null;
          rshBuilder_ = null;
        }
        if (pgrspBuilder_ == null) {
          pgrsp_ = null;
        } else {
          pgrsp_ = null;
          pgrspBuilder_ = null;
        }
        if (dprtlistBuilder_ == null) {
          dprtlist_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          dprtlistBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qlcd.qltt.body.prt.T02003001.internal_static_com_qlcd_qltt_body_prt_T02003001__rsp_descriptor;
      }

      public com.qlcd.qltt.body.prt.T02003001._rsp getDefaultInstanceForType() {
        return com.qlcd.qltt.body.prt.T02003001._rsp.getDefaultInstance();
      }

      public com.qlcd.qltt.body.prt.T02003001._rsp build() {
        com.qlcd.qltt.body.prt.T02003001._rsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qlcd.qltt.body.prt.T02003001._rsp buildPartial() {
        com.qlcd.qltt.body.prt.T02003001._rsp result = new com.qlcd.qltt.body.prt.T02003001._rsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (rshBuilder_ == null) {
          result.rsh_ = rsh_;
        } else {
          result.rsh_ = rshBuilder_.build();
        }
        if (pgrspBuilder_ == null) {
          result.pgrsp_ = pgrsp_;
        } else {
          result.pgrsp_ = pgrspBuilder_.build();
        }
        if (dprtlistBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            dprtlist_ = java.util.Collections.unmodifiableList(dprtlist_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.dprtlist_ = dprtlist_;
        } else {
          result.dprtlist_ = dprtlistBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qlcd.qltt.body.prt.T02003001._rsp) {
          return mergeFrom((com.qlcd.qltt.body.prt.T02003001._rsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qlcd.qltt.body.prt.T02003001._rsp other) {
        if (other == com.qlcd.qltt.body.prt.T02003001._rsp.getDefaultInstance()) return this;
        if (other.hasRsh()) {
          mergeRsh(other.getRsh());
        }
        if (other.hasPgrsp()) {
          mergePgrsp(other.getPgrsp());
        }
        if (dprtlistBuilder_ == null) {
          if (!other.dprtlist_.isEmpty()) {
            if (dprtlist_.isEmpty()) {
              dprtlist_ = other.dprtlist_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureDprtlistIsMutable();
              dprtlist_.addAll(other.dprtlist_);
            }
            onChanged();
          }
        } else {
          if (!other.dprtlist_.isEmpty()) {
            if (dprtlistBuilder_.isEmpty()) {
              dprtlistBuilder_.dispose();
              dprtlistBuilder_ = null;
              dprtlist_ = other.dprtlist_;
              bitField0_ = (bitField0_ & ~0x00000004);
              dprtlistBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDprtlistFieldBuilder() : null;
            } else {
              dprtlistBuilder_.addAllMessages(other.dprtlist_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qlcd.qltt.body.prt.T02003001._rsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qlcd.qltt.body.prt.T02003001._rsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.qlcd.qltt.body.BppSys._rsp_succhead rsh_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.qlcd.qltt.body.BppSys._rsp_succhead, com.qlcd.qltt.body.BppSys._rsp_succhead.Builder, com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder> rshBuilder_;
      /**
       * <code>optional .com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public boolean hasRsh() {
        return rshBuilder_ != null || rsh_ != null;
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public com.qlcd.qltt.body.BppSys._rsp_succhead getRsh() {
        if (rshBuilder_ == null) {
          return rsh_ == null ? com.qlcd.qltt.body.BppSys._rsp_succhead.getDefaultInstance() : rsh_;
        } else {
          return rshBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder setRsh(com.qlcd.qltt.body.BppSys._rsp_succhead value) {
        if (rshBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rsh_ = value;
          onChanged();
        } else {
          rshBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder setRsh(
          com.qlcd.qltt.body.BppSys._rsp_succhead.Builder builderForValue) {
        if (rshBuilder_ == null) {
          rsh_ = builderForValue.build();
          onChanged();
        } else {
          rshBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder mergeRsh(com.qlcd.qltt.body.BppSys._rsp_succhead value) {
        if (rshBuilder_ == null) {
          if (rsh_ != null) {
            rsh_ =
              com.qlcd.qltt.body.BppSys._rsp_succhead.newBuilder(rsh_).mergeFrom(value).buildPartial();
          } else {
            rsh_ = value;
          }
          onChanged();
        } else {
          rshBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public Builder clearRsh() {
        if (rshBuilder_ == null) {
          rsh_ = null;
          onChanged();
        } else {
          rsh_ = null;
          rshBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public com.qlcd.qltt.body.BppSys._rsp_succhead.Builder getRshBuilder() {
        
        onChanged();
        return getRshFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      public com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder getRshOrBuilder() {
        if (rshBuilder_ != null) {
          return rshBuilder_.getMessageOrBuilder();
        } else {
          return rsh_ == null ?
              com.qlcd.qltt.body.BppSys._rsp_succhead.getDefaultInstance() : rsh_;
        }
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppSys._rsp_succhead rsh = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.qlcd.qltt.body.BppSys._rsp_succhead, com.qlcd.qltt.body.BppSys._rsp_succhead.Builder, com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder> 
          getRshFieldBuilder() {
        if (rshBuilder_ == null) {
          rshBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.qlcd.qltt.body.BppSys._rsp_succhead, com.qlcd.qltt.body.BppSys._rsp_succhead.Builder, com.qlcd.qltt.body.BppSys._rsp_succheadOrBuilder>(
                  getRsh(),
                  getParentForChildren(),
                  isClean());
          rsh_ = null;
        }
        return rshBuilder_;
      }

      private com.qlcd.qltt.body.BppBiz._page_rsp pgrsp_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.qlcd.qltt.body.BppBiz._page_rsp, com.qlcd.qltt.body.BppBiz._page_rsp.Builder, com.qlcd.qltt.body.BppBiz._page_rspOrBuilder> pgrspBuilder_;
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      public boolean hasPgrsp() {
        return pgrspBuilder_ != null || pgrsp_ != null;
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      public com.qlcd.qltt.body.BppBiz._page_rsp getPgrsp() {
        if (pgrspBuilder_ == null) {
          return pgrsp_ == null ? com.qlcd.qltt.body.BppBiz._page_rsp.getDefaultInstance() : pgrsp_;
        } else {
          return pgrspBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      public Builder setPgrsp(com.qlcd.qltt.body.BppBiz._page_rsp value) {
        if (pgrspBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pgrsp_ = value;
          onChanged();
        } else {
          pgrspBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      public Builder setPgrsp(
          com.qlcd.qltt.body.BppBiz._page_rsp.Builder builderForValue) {
        if (pgrspBuilder_ == null) {
          pgrsp_ = builderForValue.build();
          onChanged();
        } else {
          pgrspBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      public Builder mergePgrsp(com.qlcd.qltt.body.BppBiz._page_rsp value) {
        if (pgrspBuilder_ == null) {
          if (pgrsp_ != null) {
            pgrsp_ =
              com.qlcd.qltt.body.BppBiz._page_rsp.newBuilder(pgrsp_).mergeFrom(value).buildPartial();
          } else {
            pgrsp_ = value;
          }
          onChanged();
        } else {
          pgrspBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      public Builder clearPgrsp() {
        if (pgrspBuilder_ == null) {
          pgrsp_ = null;
          onChanged();
        } else {
          pgrsp_ = null;
          pgrspBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      public com.qlcd.qltt.body.BppBiz._page_rsp.Builder getPgrspBuilder() {
        
        onChanged();
        return getPgrspFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      public com.qlcd.qltt.body.BppBiz._page_rspOrBuilder getPgrspOrBuilder() {
        if (pgrspBuilder_ != null) {
          return pgrspBuilder_.getMessageOrBuilder();
        } else {
          return pgrsp_ == null ?
              com.qlcd.qltt.body.BppBiz._page_rsp.getDefaultInstance() : pgrsp_;
        }
      }
      /**
       * <code>optional .com.qlcd.qltt.body.BppBiz._page_rsp pgrsp = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.qlcd.qltt.body.BppBiz._page_rsp, com.qlcd.qltt.body.BppBiz._page_rsp.Builder, com.qlcd.qltt.body.BppBiz._page_rspOrBuilder> 
          getPgrspFieldBuilder() {
        if (pgrspBuilder_ == null) {
          pgrspBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.qlcd.qltt.body.BppBiz._page_rsp, com.qlcd.qltt.body.BppBiz._page_rsp.Builder, com.qlcd.qltt.body.BppBiz._page_rspOrBuilder>(
                  getPgrsp(),
                  getParentForChildren(),
                  isClean());
          pgrsp_ = null;
        }
        return pgrspBuilder_;
      }

      private java.util.List<com.qlcd.qltt.body.prt.T02003001._dprealtime> dprtlist_ =
        java.util.Collections.emptyList();
      private void ensureDprtlistIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          dprtlist_ = new java.util.ArrayList<com.qlcd.qltt.body.prt.T02003001._dprealtime>(dprtlist_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.qlcd.qltt.body.prt.T02003001._dprealtime, com.qlcd.qltt.body.prt.T02003001._dprealtime.Builder, com.qlcd.qltt.body.prt.T02003001._dprealtimeOrBuilder> dprtlistBuilder_;

      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public java.util.List<com.qlcd.qltt.body.prt.T02003001._dprealtime> getDprtlistList() {
        if (dprtlistBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dprtlist_);
        } else {
          return dprtlistBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public int getDprtlistCount() {
        if (dprtlistBuilder_ == null) {
          return dprtlist_.size();
        } else {
          return dprtlistBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public com.qlcd.qltt.body.prt.T02003001._dprealtime getDprtlist(int index) {
        if (dprtlistBuilder_ == null) {
          return dprtlist_.get(index);
        } else {
          return dprtlistBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public Builder setDprtlist(
          int index, com.qlcd.qltt.body.prt.T02003001._dprealtime value) {
        if (dprtlistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDprtlistIsMutable();
          dprtlist_.set(index, value);
          onChanged();
        } else {
          dprtlistBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public Builder setDprtlist(
          int index, com.qlcd.qltt.body.prt.T02003001._dprealtime.Builder builderForValue) {
        if (dprtlistBuilder_ == null) {
          ensureDprtlistIsMutable();
          dprtlist_.set(index, builderForValue.build());
          onChanged();
        } else {
          dprtlistBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public Builder addDprtlist(com.qlcd.qltt.body.prt.T02003001._dprealtime value) {
        if (dprtlistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDprtlistIsMutable();
          dprtlist_.add(value);
          onChanged();
        } else {
          dprtlistBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public Builder addDprtlist(
          int index, com.qlcd.qltt.body.prt.T02003001._dprealtime value) {
        if (dprtlistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDprtlistIsMutable();
          dprtlist_.add(index, value);
          onChanged();
        } else {
          dprtlistBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public Builder addDprtlist(
          com.qlcd.qltt.body.prt.T02003001._dprealtime.Builder builderForValue) {
        if (dprtlistBuilder_ == null) {
          ensureDprtlistIsMutable();
          dprtlist_.add(builderForValue.build());
          onChanged();
        } else {
          dprtlistBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public Builder addDprtlist(
          int index, com.qlcd.qltt.body.prt.T02003001._dprealtime.Builder builderForValue) {
        if (dprtlistBuilder_ == null) {
          ensureDprtlistIsMutable();
          dprtlist_.add(index, builderForValue.build());
          onChanged();
        } else {
          dprtlistBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public Builder addAllDprtlist(
          java.lang.Iterable<? extends com.qlcd.qltt.body.prt.T02003001._dprealtime> values) {
        if (dprtlistBuilder_ == null) {
          ensureDprtlistIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dprtlist_);
          onChanged();
        } else {
          dprtlistBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public Builder clearDprtlist() {
        if (dprtlistBuilder_ == null) {
          dprtlist_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          dprtlistBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public Builder removeDprtlist(int index) {
        if (dprtlistBuilder_ == null) {
          ensureDprtlistIsMutable();
          dprtlist_.remove(index);
          onChanged();
        } else {
          dprtlistBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public com.qlcd.qltt.body.prt.T02003001._dprealtime.Builder getDprtlistBuilder(
          int index) {
        return getDprtlistFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public com.qlcd.qltt.body.prt.T02003001._dprealtimeOrBuilder getDprtlistOrBuilder(
          int index) {
        if (dprtlistBuilder_ == null) {
          return dprtlist_.get(index);  } else {
          return dprtlistBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public java.util.List<? extends com.qlcd.qltt.body.prt.T02003001._dprealtimeOrBuilder> 
           getDprtlistOrBuilderList() {
        if (dprtlistBuilder_ != null) {
          return dprtlistBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dprtlist_);
        }
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public com.qlcd.qltt.body.prt.T02003001._dprealtime.Builder addDprtlistBuilder() {
        return getDprtlistFieldBuilder().addBuilder(
            com.qlcd.qltt.body.prt.T02003001._dprealtime.getDefaultInstance());
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public com.qlcd.qltt.body.prt.T02003001._dprealtime.Builder addDprtlistBuilder(
          int index) {
        return getDprtlistFieldBuilder().addBuilder(
            index, com.qlcd.qltt.body.prt.T02003001._dprealtime.getDefaultInstance());
      }
      /**
       * <code>repeated .com.qlcd.qltt.body.prt.T02003001._dprealtime dprtlist = 3;</code>
       */
      public java.util.List<com.qlcd.qltt.body.prt.T02003001._dprealtime.Builder> 
           getDprtlistBuilderList() {
        return getDprtlistFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.qlcd.qltt.body.prt.T02003001._dprealtime, com.qlcd.qltt.body.prt.T02003001._dprealtime.Builder, com.qlcd.qltt.body.prt.T02003001._dprealtimeOrBuilder> 
          getDprtlistFieldBuilder() {
        if (dprtlistBuilder_ == null) {
          dprtlistBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.qlcd.qltt.body.prt.T02003001._dprealtime, com.qlcd.qltt.body.prt.T02003001._dprealtime.Builder, com.qlcd.qltt.body.prt.T02003001._dprealtimeOrBuilder>(
                  dprtlist_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          dprtlist_ = null;
        }
        return dprtlistBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.qlcd.qltt.body.prt.T02003001._rsp)
    }

    // @@protoc_insertion_point(class_scope:com.qlcd.qltt.body.prt.T02003001._rsp)
    private static final com.qlcd.qltt.body.prt.T02003001._rsp defaultInstance;static {
      defaultInstance = new com.qlcd.qltt.body.prt.T02003001._rsp();
    }

    public static com.qlcd.qltt.body.prt.T02003001._rsp getDefaultInstance() {
      return defaultInstance;
    }

    public com.qlcd.qltt.body.prt.T02003001._rsp getDefaultInstanceForType() {
      return defaultInstance;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qlcd_qltt_body_prt_T02003001__req_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qlcd_qltt_body_prt_T02003001__req_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qlcd_qltt_body_prt_T02003001__dprealtime_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qlcd_qltt_body_prt_T02003001__dprealtime_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qlcd_qltt_body_prt_T02003001__rsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qlcd_qltt_body_prt_T02003001__rsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023prt/T02003001.proto\022 com.qlcd.qltt.bod" +
      "y.prt.T02003001\032\014BppSys.proto\032\014BppBiz.pr" +
      "oto\"[\n\004_req\0223\n\005pgreq\030\001 \001(\0132$.com.qlcd.ql" +
      "tt.body.BppBiz._page_req\022\016\n\006tactic\030\002 \001(\t" +
      "\022\016\n\006tacprm\030\003 \001(\005\"\220\001\n\013_dprealtime\022\016\n\006tact" +
      "ic\030\001 \001(\t\022\016\n\006tacprm\030\002 \001(\005\022\r\n\005index\030\003 \001(\005\022" +
      "\021\n\tstockcode\030\004 \001(\t\022\016\n\006occval\030\005 \001(\t\022\017\n\007re" +
      "marks\030\006 \001(\t\022\017\n\007efftime\030\007 \001(\t\022\r\n\005count\030\010 " +
      "\001(\005\"\263\001\n\004_rsp\0225\n\003rsh\030\001 \001(\0132(.com.qlcd.qlt" +
      "t.body.BppSys._rsp_succhead\0223\n\005pgrsp\030\002 \001",
      "(\0132$.com.qlcd.qltt.body.BppBiz._page_rsp" +
      "\022?\n\010dprtlist\030\003 \003(\0132-.com.qlcd.qltt.body." +
      "prt.T02003001._dprealtimeB\030\n\026com.qlcd.ql" +
      "tt.body.prtb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.qlcd.qltt.body.BppSys.getDescriptor(),
          com.qlcd.qltt.body.BppBiz.getDescriptor(),
        }, assigner);
    internal_static_com_qlcd_qltt_body_prt_T02003001__req_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_qlcd_qltt_body_prt_T02003001__req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_qlcd_qltt_body_prt_T02003001__req_descriptor,
        new java.lang.String[] { "Pgreq", "Tactic", "Tacprm", });
    internal_static_com_qlcd_qltt_body_prt_T02003001__dprealtime_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_qlcd_qltt_body_prt_T02003001__dprealtime_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_qlcd_qltt_body_prt_T02003001__dprealtime_descriptor,
        new java.lang.String[] { "Tactic", "Tacprm", "Index", "Stockcode", "Occval", "Remarks", "Efftime", "Count", });
    internal_static_com_qlcd_qltt_body_prt_T02003001__rsp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_qlcd_qltt_body_prt_T02003001__rsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_qlcd_qltt_body_prt_T02003001__rsp_descriptor,
        new java.lang.String[] { "Rsh", "Pgrsp", "Dprtlist", });
    com.qlcd.qltt.body.BppSys.getDescriptor();
    com.qlcd.qltt.body.BppBiz.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
